
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mul 

module det_stoch_mul(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g8(.A (a), .B (b), .Y (y));
endmodule

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_3(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_16));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_3 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g12(.A (e), .Y (n_6));
  OAI21X1 g71(.A (n_6), .B (n_1), .C (n_2), .Y (a_gt_b));
  AOI21X1 g72(.A (e_13), .B (n_4), .C (agt), .Y (n_5));
  INVX1 g73(.A (n_0), .Y (n_4));
  AOI21X1 g74(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_3));
  INVX1 g75(.A (agt_9), .Y (n_2));
  BUFX2 drc_bufs(.A (n_5), .Y (n_1));
  BUFX2 drc_bufs76(.A (n_3), .Y (n_0));
endmodule

module counter_WIDTH4(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_26, n_27, n_28, n_29;
  DFFSR \out_reg[3] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_26));
  DFFSR overflow_reg(.R (n_7), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (overflow));
  INVX1 g65(.A (n_20), .Y (n_21));
  MUX2X1 g66(.A (n_16), .B (overflow), .S (en), .Y (n_20));
  INVX1 g67(.A (n_18), .Y (n_19));
  MUX2X1 g68(.A (n_17), .B (out[3]), .S (en), .Y (n_18));
  DFFSR \out_reg[2] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_27));
  HAX1 g70(.A (out[3]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g71(.A (n_14), .Y (n_15));
  MUX2X1 g72(.A (n_13), .B (out[2]), .S (en), .Y (n_14));
  DFFSR \out_reg[1] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_28));
  HAX1 g74(.A (out[2]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g75(.A (n_10), .Y (n_11));
  MUX2X1 g76(.A (n_9), .B (out[1]), .S (en), .Y (n_10));
  DFFSR \out_reg[0] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_29));
  HAX1 g78(.A (out[1]), .B (out[0]), .YC (n_8), .YS (n_9));
  INVX1 g89(.A (rst), .Y (n_7));
  BUFX2 drc_bufs109(.A (n_29), .Y (out[0]));
  BUFX2 drc_bufs111(.A (n_26), .Y (out[3]));
  BUFX2 drc_bufs112(.A (n_27), .Y (out[2]));
  BUFX2 drc_bufs113(.A (n_28), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_4b(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  comp_4b comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module comp_1b_4(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_5(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_6(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_7(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b_1(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED0, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b_4 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED0),
       .a_larger (agt_16));
  comp_1b_5 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_6 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_7 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g12(.A (e), .Y (n_6));
  OAI21X1 g71(.A (n_6), .B (n_1), .C (n_2), .Y (a_gt_b));
  AOI21X1 g72(.A (e_13), .B (n_4), .C (agt), .Y (n_5));
  INVX1 g73(.A (n_0), .Y (n_4));
  AOI21X1 g74(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_3));
  INVX1 g75(.A (agt_9), .Y (n_2));
  BUFX2 drc_bufs(.A (n_5), .Y (n_1));
  BUFX2 drc_bufs76(.A (n_3), .Y (n_0));
endmodule

module counter_WIDTH4_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_1, n_3, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_20, n_21, n_25, n_27;
  wire n_28, n_29, n_30, n_31, n_32;
  DFFSR \out_reg[3] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_32), .Q
       (n_27));
  DFFSR \out_reg[2] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_28));
  INVX1 g108(.A (n_20), .Y (n_21));
  MUX2X1 g109(.A (n_17), .B (out[2]), .S (en), .Y (n_20));
  DFFSR overflow_reg(.R (n_10), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_25));
  DFFSR \out_reg[1] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_29));
  MUX2X1 g113(.A (n_1), .B (n_3), .S (en), .Y (n_18));
  HAX1 g114(.A (out[2]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g115(.A (n_14), .Y (n_15));
  MUX2X1 g116(.A (n_11), .B (out[1]), .S (en), .Y (n_14));
  NAND3X1 g117(.A (out[2]), .B (out[3]), .C (n_12), .Y (n_13));
  DFFSR \out_reg[0] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_30));
  HAX1 g119(.A (out[1]), .B (out[0]), .YC (n_12), .YS (n_11));
  INVX1 g135(.A (rst), .Y (n_10));
  INVX1 drc_bufs137(.A (overflow), .Y (n_3));
  BUFX2 drc_bufs155(.A (n_13), .Y (n_1));
  BUFX2 drc_bufs156(.A (n_30), .Y (out[0]));
  BUFX2 drc_bufs157(.A (n_29), .Y (out[1]));
  BUFX2 drc_bufs158(.A (n_25), .Y (overflow));
  BUFX2 drc_bufs159(.A (n_27), .Y (out[3]));
  BUFX2 drc_bufs160(.A (n_28), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g167(.A (n_31), .B (out[3]), .Y (n_32));
  AND2X1 g3(.A (n_16), .B (en), .Y (n_31));
endmodule

module prg_4b_1(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  comp_4b_1 comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4_1 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module counter_WIDTH8(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [7:0] out;
  output overflow;
  wire clk, en, rst;
  wire [7:0] out;
  wire overflow;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_26, n_27, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_50, n_51;
  DFFSR \out_reg[7] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_51), .Q
       (n_37));
  DFFSR \out_reg[6] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_27), .Q
       (n_36));
  INVX1 g132(.A (n_26), .Y (n_27));
  MUX2X1 g133(.A (n_24), .B (out[6]), .S (en), .Y (n_26));
  DFFSR \out_reg[5] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_22), .Q
       (n_35));
  HAX1 g136(.A (out[6]), .B (n_19), .YC (n_23), .YS (n_24));
  INVX1 g137(.A (n_21), .Y (n_22));
  MUX2X1 g138(.A (n_20), .B (out[5]), .S (en), .Y (n_21));
  DFFSR \out_reg[4] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_34));
  HAX1 g140(.A (out[5]), .B (n_15), .YC (n_19), .YS (n_20));
  INVX1 g141(.A (n_17), .Y (n_18));
  MUX2X1 g142(.A (n_16), .B (out[4]), .S (en), .Y (n_17));
  DFFSR \out_reg[3] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_33));
  HAX1 g144(.A (out[4]), .B (n_11), .YC (n_15), .YS (n_16));
  INVX1 g145(.A (n_13), .Y (n_14));
  MUX2X1 g146(.A (n_12), .B (out[3]), .S (en), .Y (n_13));
  DFFSR \out_reg[2] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_10), .Q
       (n_32));
  HAX1 g148(.A (out[3]), .B (n_7), .YC (n_11), .YS (n_12));
  INVX1 g149(.A (n_9), .Y (n_10));
  MUX2X1 g150(.A (n_8), .B (out[2]), .S (en), .Y (n_9));
  DFFSR \out_reg[1] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_6), .Q
       (n_31));
  HAX1 g152(.A (out[2]), .B (n_3), .YC (n_7), .YS (n_8));
  INVX1 g153(.A (n_5), .Y (n_6));
  MUX2X1 g154(.A (n_4), .B (out[1]), .S (en), .Y (n_5));
  DFFSR \out_reg[0] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_30));
  HAX1 g156(.A (out[1]), .B (out[0]), .YC (n_3), .YS (n_4));
  INVX1 g174(.A (rst), .Y (n_2));
  BUFX2 drc_bufs207(.A (n_37), .Y (out[7]));
  BUFX2 drc_bufs208(.A (n_30), .Y (out[0]));
  BUFX2 drc_bufs209(.A (n_31), .Y (out[1]));
  BUFX2 drc_bufs210(.A (n_32), .Y (out[2]));
  BUFX2 drc_bufs211(.A (n_33), .Y (out[3]));
  BUFX2 drc_bufs212(.A (n_34), .Y (out[4]));
  BUFX2 drc_bufs213(.A (n_35), .Y (out[5]));
  BUFX2 drc_bufs214(.A (n_36), .Y (out[6]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g223(.A (n_50), .B (out[7]), .Y (n_51));
  AND2X1 g3(.A (en), .B (n_23), .Y (n_50));
endmodule

module dsc_mul(a, b, z, clk, rst, en, ov);
  input [3:0] a, b;
  input clk, rst, en;
  output [7:0] z;
  output ov;
  wire [3:0] a, b;
  wire clk, rst, en;
  wire [7:0] z;
  wire ov;
  wire ctr_ov_a, ctr_ov_b, dummy_ov, n_0, sn_out_a, sn_out_b,
       sn_out_mul;
  det_stoch_mul mul(.a (sn_out_a), .b (sn_out_b), .y (sn_out_mul));
  prg_4b prg_a(.clk (clk), .rst (rst), .en (en), .bin_in (a), .sn_out
       (sn_out_a), .ctr_overflow (ctr_ov_a));
  prg_4b_1 prg_b(.clk (ctr_ov_a), .rst (rst), .en (en), .bin_in (b),
       .sn_out (sn_out_b), .ctr_overflow (ctr_ov_b));
  counter_WIDTH8 stoch2bin_out(.out (z), .clk (clk), .en (sn_out_mul),
       .rst (rst), .overflow (dummy_ov));
  OR2X1 g4(.A (ctr_ov_b), .B (n_0), .Y (ov));
  INVX1 g5(.A (sn_out_b), .Y (n_0));
endmodule

