
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mul 

module prg_4b_by2_1(clk, rst, en, bin_in, sn_out0, sn_out1,
     ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out0, sn_out1, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out0, sn_out1, ctr_overflow;
  wire [3:0] ctr4_out;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30;
  OAI21X1 g190(.A (n_18), .B (n_27), .C (n_19), .Y (sn_out0));
  AOI22X1 g192(.A (n_29), .B (n_25), .C (bin_in[3]), .D (n_23), .Y
       (n_30));
  OAI21X1 g193(.A (n_21), .B (ctr4_out[2]), .C (n_17), .Y (n_29));
  NAND2X1 g194(.A (n_24), .B (n_25), .Y (n_28));
  OAI21X1 g195(.A (bin_in[1]), .B (n_22), .C (bin_in[0]), .Y (n_27));
  NAND3X1 g196(.A (bin_in[1]), .B (n_24), .C (n_22), .Y (n_26));
  OR2X1 g197(.A (n_23), .B (bin_in[3]), .Y (n_25));
  OR2X1 g198(.A (n_20), .B (bin_in[2]), .Y (n_24));
  INVX1 g199(.A (ctr4_out[3]), .Y (n_23));
  INVX1 g200(.A (ctr4_out[1]), .Y (n_22));
  INVX1 g201(.A (bin_in[2]), .Y (n_21));
  INVX1 g202(.A (ctr4_out[2]), .Y (n_20));
  INVX1 drc_bufs204(.A (n_19), .Y (sn_out1));
  BUFX2 drc_bufs206(.A (n_28), .Y (n_18));
  BUFX2 drc_bufs207(.A (n_26), .Y (n_17));
  BUFX2 drc_bufs208(.A (n_30), .Y (n_19));
  DFFSR \ctr4_out_reg[3] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_12),
       .Q (n_13));
  DFFSR ctr4_overflow_reg(.R (n_2), .S (1'b1), .CLK (clk), .D (n_10),
       .Q (n_16));
  INVX1 g101(.A (n_11), .Y (n_12));
  MUX2X1 g102(.A (n_8), .B (ctr4_out[3]), .S (en), .Y (n_11));
  INVX1 g103(.A (n_9), .Y (n_10));
  MUX2X1 g104(.A (n_7), .B (ctr_overflow), .S (en), .Y (n_9));
  DFFSR \ctr4_out_reg[2] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_6), .Q
       (n_14));
  HAX1 g106(.A (ctr4_out[3]), .B (n_3), .YC (n_7), .YS (n_8));
  INVX1 g107(.A (n_5), .Y (n_6));
  MUX2X1 g108(.A (n_4), .B (ctr4_out[2]), .S (en), .Y (n_5));
  DFFSR \ctr4_out_reg[1] (.R (n_2), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_15));
  HAX1 g110(.A (ctr4_out[2]), .B (ctr4_out[1]), .YC (n_3), .YS (n_4));
  INVX1 g119(.A (rst), .Y (n_2));
  BUFX2 drc_bufs135(.A (n_16), .Y (ctr_overflow));
  BUFX2 drc_bufs136(.A (n_13), .Y (ctr4_out[3]));
  BUFX2 drc_bufs137(.A (n_14), .Y (ctr4_out[2]));
  BUFX2 drc_bufs138(.A (n_15), .Y (ctr4_out[1]));
  XOR2X1 g2(.A (en), .B (ctr4_out[1]), .Y (n_0));
endmodule

module dsc_mul(a, b, z, clk, rst, en, ov);
  input [3:0] a, b;
  input clk, rst, en;
  output [7:0] z;
  output ov;
  wire [3:0] a, b;
  wire clk, rst, en;
  wire [7:0] z;
  wire ov;
  wire [3:0] prg_a_ctr4_out;
  wire ctr_ov_a, ctr_ov_b, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, sn_out_b0, sn_out_b1;
  prg_4b_by2_1 prg_b(.clk (ctr_ov_a), .rst (rst), .en (en), .bin_in
       (b), .sn_out0 (sn_out_b0), .sn_out1 (sn_out_b1), .ctr_overflow
       (ctr_ov_b));
  OAI21X1 g70(.A (sn_out_b1), .B (sn_out_b0), .C (n_93), .Y (ov));
  INVX1 g71(.A (ctr_ov_b), .Y (n_93));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[7] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_83), .Q (n_92));
  OAI21X1 g387(.A (n_54), .B (n_80), .C (n_2), .Y (n_83));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[6] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_82), .Q (n_91));
  INVX1 g389(.A (n_81), .Y (n_82));
  MUX2X1 g390(.A (z[6]), .B (n_79), .S (n_54), .Y (n_81));
  XNOR2X1 g391(.A (n_78), .B (z[7]), .Y (n_80));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[5] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_77), .Q (n_90));
  HAX1 g393(.A (z[6]), .B (n_74), .YC (n_78), .YS (n_79));
  INVX1 g394(.A (n_76), .Y (n_77));
  MUX2X1 g395(.A (z[5]), .B (n_75), .S (n_54), .Y (n_76));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[4] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_73), .Q (n_89));
  HAX1 g397(.A (z[5]), .B (n_70), .YC (n_74), .YS (n_75));
  INVX1 g398(.A (n_72), .Y (n_73));
  MUX2X1 g399(.A (z[4]), .B (n_71), .S (n_54), .Y (n_72));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[3] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_69), .Q (n_88));
  HAX1 g401(.A (z[4]), .B (n_66), .YC (n_70), .YS (n_71));
  INVX1 g402(.A (n_68), .Y (n_69));
  MUX2X1 g403(.A (z[3]), .B (n_67), .S (n_54), .Y (n_68));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[2] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_65), .Q (n_87));
  HAX1 g405(.A (z[3]), .B (n_63), .YC (n_66), .YS (n_67));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[1] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_64), .Q (n_86));
  MUX2X1 g407(.A (n_8), .B (n_62), .S (n_54), .Y (n_65));
  MUX2X1 g408(.A (n_10), .B (n_60), .S (n_54), .Y (n_64));
  AND2X1 g409(.A (n_3), .B (z[2]), .Y (n_63));
  XNOR2X1 g410(.A (n_59), .B (n_47), .Y (n_62));
  DFFSR \stoch2bin_out_stoch2bin_out_out_reg[0] (.R (n_12), .S (1'b1),
       .CLK (clk), .D (n_58), .Q (n_85));
  NAND2X1 g412(.A (n_45), .B (n_59), .Y (n_61));
  XOR2X1 g413(.A (n_55), .B (n_53), .Y (n_60));
  OAI21X1 g414(.A (n_51), .B (n_53), .C (z[1]), .Y (n_59));
  INVX1 g415(.A (n_57), .Y (n_58));
  MUX2X1 g416(.A (z[0]), .B (n_52), .S (n_54), .Y (n_57));
  NAND2X1 g417(.A (z[7]), .B (n_54), .Y (n_56));
  MUX2X1 g418(.A (n_10), .B (z[1]), .S (n_51), .Y (n_55));
  NOR3X1 g419(.A (n_44), .B (n_50), .C (n_51), .Y (n_54));
  HAX1 g420(.A (z[0]), .B (n_50), .YC (n_53), .YS (n_52));
  XNOR2X1 g421(.A (n_49), .B (n_35), .Y (n_51));
  HAX1 g422(.A (n_38), .B (n_48), .YC (n_49), .YS (n_50));
  OR2X1 g423(.A (n_46), .B (n_44), .Y (n_48));
  MUX2X1 g424(.A (z[2]), .B (n_8), .S (n_45), .Y (n_47));
  AND2X1 g425(.A (n_43), .B (n_35), .Y (n_46));
  INVX1 g426(.A (n_44), .Y (n_45));
  HAX1 g428(.A (n_36), .B (n_37), .YC (n_44), .YS (n_43));
  DFFSR \prg_a_ctr4_out_reg[3] (.R (n_12), .S (1'b1), .CLK (clk), .D
       (n_42), .Q (prg_a_ctr4_out[3]));
  DFFSR prg_a_ctr4_overflow_reg(.R (n_12), .S (1'b1), .CLK (clk), .D
       (n_40), .Q (ctr_ov_a));
  INVX1 g431(.A (n_41), .Y (n_42));
  MUX2X1 g432(.A (n_32), .B (n_7), .S (en), .Y (n_41));
  INVX1 g433(.A (n_39), .Y (n_40));
  MUX2X1 g434(.A (n_31), .B (ctr_ov_a), .S (en), .Y (n_39));
  AND2X1 g435(.A (n_34), .B (sn_out_b0), .Y (n_38));
  AND2X1 g436(.A (n_34), .B (sn_out_b1), .Y (n_37));
  DFFSR \prg_a_ctr4_out_reg[2] (.R (n_12), .S (1'b1), .CLK (clk), .D
       (n_29), .Q (prg_a_ctr4_out[2]));
  AND2X1 g438(.A (n_30), .B (sn_out_b0), .Y (n_36));
  OAI21X1 g439(.A (n_25), .B (n_26), .C (sn_out_b1), .Y (n_35));
  INVX1 g440(.A (n_1), .Y (n_34));
  AOI21X1 g441(.A (a[0]), .B (n_27), .C (n_30), .Y (n_33));
  HAX1 g442(.A (n_7), .B (n_21), .YC (n_31), .YS (n_32));
  OR2X1 g443(.A (n_26), .B (n_25), .Y (n_30));
  INVX1 g444(.A (n_28), .Y (n_29));
  MUX2X1 g445(.A (n_22), .B (n_6), .S (en), .Y (n_28));
  OAI21X1 g446(.A (n_20), .B (n_17), .C (n_24), .Y (n_27));
  AND2X1 g447(.A (n_23), .B (a[1]), .Y (n_26));
  DFFSR \prg_a_ctr4_out_reg[1] (.R (n_12), .S (1'b1), .CLK (clk), .D
       (n_0), .Q (prg_a_ctr4_out[1]));
  OAI21X1 g449(.A (n_15), .B (n_7), .C (n_19), .Y (n_25));
  INVX1 g450(.A (n_23), .Y (n_24));
  NOR3X1 g451(.A (n_5), .B (n_16), .C (n_17), .Y (n_23));
  HAX1 g452(.A (n_6), .B (n_5), .YC (n_21), .YS (n_22));
  OR2X1 g453(.A (n_16), .B (n_13), .Y (n_20));
  OR2X1 g454(.A (n_17), .B (n_4), .Y (n_19));
  NAND2X1 g456(.A (a[2]), .B (n_9), .Y (n_18));
  AND2X1 g457(.A (n_7), .B (n_15), .Y (n_17));
  AND2X1 g458(.A (n_6), .B (n_14), .Y (n_16));
  INVX1 g474(.A (a[3]), .Y (n_15));
  INVX1 g475(.A (a[2]), .Y (n_14));
  INVX1 g477(.A (a[1]), .Y (n_13));
  INVX1 g478(.A (rst), .Y (n_12));
  INVX1 drc_bufs480(.A (z[2]), .Y (n_8));
  INVX1 drc_bufs484(.A (z[1]), .Y (n_10));
  INVX1 drc_bufs516(.A (n_6), .Y (n_9));
  BUFX2 drc_bufs526(.A (n_18), .Y (n_4));
  BUFX2 drc_bufs527(.A (n_61), .Y (n_3));
  BUFX2 drc_bufs528(.A (n_56), .Y (n_2));
  BUFX2 drc_bufs529(.A (n_33), .Y (n_1));
  BUFX2 drc_bufs530(.A (n_92), .Y (z[7]));
  BUFX2 drc_bufs531(.A (n_91), .Y (z[6]));
  BUFX2 drc_bufs532(.A (n_89), .Y (z[4]));
  BUFX2 drc_bufs533(.A (n_85), .Y (z[0]));
  BUFX2 drc_bufs535(.A (prg_a_ctr4_out[3]), .Y (n_7));
  BUFX2 drc_bufs536(.A (prg_a_ctr4_out[2]), .Y (n_6));
  BUFX2 drc_bufs537(.A (n_88), .Y (z[3]));
  BUFX2 drc_bufs538(.A (prg_a_ctr4_out[1]), .Y (n_5));
  BUFX2 drc_bufs539(.A (n_90), .Y (z[5]));
  BUFX2 drc_bufs540(.A (n_86), .Y (z[1]));
  BUFX2 drc_bufs541(.A (n_87), .Y (z[2]));
  XOR2X1 g2(.A (en), .B (n_5), .Y (n_0));
endmodule

