
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mul 

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_3(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_4(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_5(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_28));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_3 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_4 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger (agt));
  comp_1b_5 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger (agt_17));
  INVX1 g19(.A (e), .Y (n_11));
  INVX1 g18(.A (e_14), .Y (n_10));
  OAI21X1 g141(.A (n_11), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_10), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_6(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_7(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_8(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_9(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_10(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_11(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_1(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED0, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_6 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED0),
       .a_larger (agt_28));
  comp_1b_7 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_8 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_9 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_10 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_11 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_12(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_13(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_14(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_15(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_16(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_17(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_2(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED1, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_12 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED1),
       .a_larger (agt_28));
  comp_1b_13 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_14 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_15 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_16 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_17 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_18(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_19(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_20(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_21(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_22(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_23(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_3(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED2, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_18 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED2),
       .a_larger (agt_28));
  comp_1b_19 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_20 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_21 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_22 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_23 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module counter_WIDTH6(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [5:0] out;
  output overflow;
  wire clk, en, rst;
  wire [5:0] out;
  wire overflow;
  wire n_0, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_35, n_36, n_37, n_38, n_39, n_40;
  DFFSR \out_reg[5] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_35));
  DFFSR overflow_reg(.R (n_9), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (overflow));
  INVX1 g93(.A (n_30), .Y (n_31));
  MUX2X1 g94(.A (n_26), .B (overflow), .S (en), .Y (n_30));
  INVX1 g95(.A (n_28), .Y (n_29));
  MUX2X1 g96(.A (n_27), .B (out[5]), .S (en), .Y (n_28));
  DFFSR \out_reg[4] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_36));
  HAX1 g98(.A (out[5]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g99(.A (n_24), .Y (n_25));
  MUX2X1 g100(.A (n_23), .B (out[4]), .S (en), .Y (n_24));
  DFFSR \out_reg[3] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_37));
  HAX1 g102(.A (out[4]), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g103(.A (n_20), .Y (n_21));
  MUX2X1 g104(.A (n_19), .B (out[3]), .S (en), .Y (n_20));
  DFFSR \out_reg[2] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_38));
  HAX1 g106(.A (out[3]), .B (n_14), .YC (n_18), .YS (n_19));
  INVX1 g107(.A (n_16), .Y (n_17));
  MUX2X1 g108(.A (n_15), .B (out[2]), .S (en), .Y (n_16));
  DFFSR \out_reg[1] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_39));
  HAX1 g110(.A (out[2]), .B (n_10), .YC (n_14), .YS (n_15));
  INVX1 g111(.A (n_12), .Y (n_13));
  MUX2X1 g112(.A (n_11), .B (out[1]), .S (en), .Y (n_12));
  DFFSR \out_reg[0] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_40));
  HAX1 g114(.A (out[1]), .B (out[0]), .YC (n_10), .YS (n_11));
  INVX1 g128(.A (rst), .Y (n_9));
  BUFX2 drc_bufs157(.A (n_40), .Y (out[0]));
  BUFX2 drc_bufs159(.A (n_35), .Y (out[5]));
  BUFX2 drc_bufs160(.A (n_36), .Y (out[4]));
  BUFX2 drc_bufs161(.A (n_37), .Y (out[3]));
  BUFX2 drc_bufs162(.A (n_38), .Y (out[2]));
  BUFX2 drc_bufs163(.A (n_39), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_6b_quad(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire [5:0] ctr4_out;
  comp_6b comp6_a(.a_gt_b (sn_out_a), .a (bin_in_a), .b (ctr4_out));
  comp_6b_1 comp6_b(.a_gt_b (sn_out_b), .a (bin_in_b), .b (ctr4_out));
  comp_6b_2 comp6_c(.a_gt_b (sn_out_c), .a (bin_in_c), .b (ctr4_out));
  comp_6b_3 comp6_d(.a_gt_b (sn_out_d), .a (bin_in_d), .b (ctr4_out));
  counter_WIDTH6 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module prg_6b_4in_max(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out, ctr_overflow;
  wire n_0, n_1, sn_out_a, sn_out_b, sn_out_c, sn_out_d;
  prg_6b_quad prg_ab(.clk (clk), .rst (rst), .en (en), .bin_in_a
       (bin_in_a), .bin_in_b (bin_in_b), .bin_in_c (bin_in_c),
       .bin_in_d (bin_in_d), .sn_out_a (sn_out_a), .sn_out_b
       (sn_out_b), .sn_out_c (sn_out_c), .sn_out_d (sn_out_d),
       .ctr_overflow (ctr_overflow));
  OR2X1 g19(.A (n_0), .B (n_1), .Y (sn_out));
  OR2X1 g20(.A (sn_out_b), .B (sn_out_a), .Y (n_1));
  OR2X1 g21(.A (sn_out_d), .B (sn_out_c), .Y (n_0));
endmodule

module comp_1b_24(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_25(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_26(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_27(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_28(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_29(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_4(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED3, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_24 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED3),
       .a_larger (agt_28));
  comp_1b_25 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_26 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_27 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_28 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_29 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g19(.A (e), .Y (n_11));
  INVX1 g18(.A (e_14), .Y (n_10));
  OAI21X1 g141(.A (n_11), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_10), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_30(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_31(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_32(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_33(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_34(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_35(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_5(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED4, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_30 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED4),
       .a_larger (agt_28));
  comp_1b_31 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_32 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_33 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_34 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_35 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_36(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_37(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_38(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_39(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_40(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_41(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_6(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED5, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_36 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED5),
       .a_larger (agt_28));
  comp_1b_37 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_38 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_39 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_40 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_41 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_42(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_43(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_44(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_45(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_46(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_47(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_7(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED6, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_42 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED6),
       .a_larger (agt_28));
  comp_1b_43 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_44 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_45 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_46 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_47 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module counter_WIDTH6_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [5:0] out;
  output overflow;
  wire clk, en, rst;
  wire [5:0] out;
  wire overflow;
  wire n_0, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_35, n_36, n_37, n_38, n_39, n_40;
  DFFSR \out_reg[5] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_35));
  DFFSR overflow_reg(.R (n_9), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (overflow));
  INVX1 g181(.A (n_30), .Y (n_31));
  MUX2X1 g182(.A (n_26), .B (overflow), .S (en), .Y (n_30));
  INVX1 g183(.A (n_28), .Y (n_29));
  MUX2X1 g184(.A (n_27), .B (out[5]), .S (en), .Y (n_28));
  DFFSR \out_reg[4] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_36));
  HAX1 g186(.A (out[5]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g187(.A (n_24), .Y (n_25));
  MUX2X1 g188(.A (n_23), .B (out[4]), .S (en), .Y (n_24));
  DFFSR \out_reg[3] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_37));
  HAX1 g190(.A (out[4]), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g191(.A (n_20), .Y (n_21));
  MUX2X1 g192(.A (n_19), .B (out[3]), .S (en), .Y (n_20));
  DFFSR \out_reg[2] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_38));
  HAX1 g194(.A (out[3]), .B (n_14), .YC (n_18), .YS (n_19));
  INVX1 g195(.A (n_16), .Y (n_17));
  MUX2X1 g196(.A (n_15), .B (out[2]), .S (en), .Y (n_16));
  DFFSR \out_reg[1] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_39));
  HAX1 g198(.A (out[2]), .B (n_10), .YC (n_14), .YS (n_15));
  INVX1 g199(.A (n_12), .Y (n_13));
  MUX2X1 g200(.A (n_11), .B (out[1]), .S (en), .Y (n_12));
  DFFSR \out_reg[0] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_40));
  HAX1 g202(.A (out[1]), .B (out[0]), .YC (n_10), .YS (n_11));
  INVX1 g216(.A (rst), .Y (n_9));
  BUFX2 drc_bufs245(.A (n_40), .Y (out[0]));
  BUFX2 drc_bufs247(.A (n_35), .Y (out[5]));
  BUFX2 drc_bufs248(.A (n_36), .Y (out[4]));
  BUFX2 drc_bufs249(.A (n_37), .Y (out[3]));
  BUFX2 drc_bufs250(.A (n_38), .Y (out[2]));
  BUFX2 drc_bufs251(.A (n_39), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_6b_quad_1(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire [5:0] ctr4_out;
  comp_6b_4 comp6_a(.a_gt_b (sn_out_a), .a (bin_in_a), .b (ctr4_out));
  comp_6b_5 comp6_b(.a_gt_b (sn_out_b), .a (bin_in_b), .b (ctr4_out));
  comp_6b_6 comp6_c(.a_gt_b (sn_out_c), .a (bin_in_c), .b (ctr4_out));
  comp_6b_7 comp6_d(.a_gt_b (sn_out_d), .a (bin_in_d), .b (ctr4_out));
  counter_WIDTH6_1 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module prg_6b_4in_lowmid(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out, ctr_overflow;
  wire UNCONNECTED7, n_0, n_2, n_4, n_34, sn_out_a, sn_out_b, sn_out_c;
  wire sn_out_d;
  prg_6b_quad_1 prg_ab(.clk (clk), .rst (rst), .en (en), .bin_in_a
       (bin_in_a), .bin_in_b (bin_in_b), .bin_in_c (bin_in_c),
       .bin_in_d (bin_in_d), .sn_out_a (sn_out_a), .sn_out_b
       (sn_out_b), .sn_out_c (sn_out_c), .sn_out_d (sn_out_d),
       .ctr_overflow (ctr_overflow));
  INVX1 g8(.A (sn_out_d), .Y (n_4));
  OAI21X1 g67(.A (n_4), .B (n_2), .C (n_0), .Y (sn_out));
  NOR3X1 g69(.A (sn_out_b), .B (sn_out_c), .C (sn_out_a), .Y (n_2));
  INVX1 g3(.A (n_34), .Y (n_0));
  FAX1 g2(.A (sn_out_a), .B (sn_out_b), .C (sn_out_c), .YC (n_34), .YS
       (UNCONNECTED7));
endmodule

module comp_1b_48(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_49(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_50(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_51(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_52(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_53(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_8(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED8, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_48 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED8),
       .a_larger (agt_28));
  comp_1b_49 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_50 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_51 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_52 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_53 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_54(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_55(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_56(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_57(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_58(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_59(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_9(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED9, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_54 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED9),
       .a_larger (agt_28));
  comp_1b_55 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_56 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_57 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_58 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_59 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_60(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_61(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_62(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_63(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_64(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_65(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_10(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED10, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_60 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED10),
       .a_larger (agt_28));
  comp_1b_61 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_62 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_63 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_64 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_65 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_66(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_67(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_68(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_69(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_70(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_71(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_11(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED11, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_66 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED11),
       .a_larger (agt_28));
  comp_1b_67 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_68 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_69 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_70 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_71 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module counter_WIDTH6_2(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [5:0] out;
  output overflow;
  wire clk, en, rst;
  wire [5:0] out;
  wire overflow;
  wire n_0, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_35, n_36, n_37, n_38, n_39, n_40;
  DFFSR \out_reg[5] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_35));
  DFFSR overflow_reg(.R (n_9), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (overflow));
  INVX1 g181(.A (n_30), .Y (n_31));
  MUX2X1 g182(.A (n_26), .B (overflow), .S (en), .Y (n_30));
  INVX1 g183(.A (n_28), .Y (n_29));
  MUX2X1 g184(.A (n_27), .B (out[5]), .S (en), .Y (n_28));
  DFFSR \out_reg[4] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_36));
  HAX1 g186(.A (out[5]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g187(.A (n_24), .Y (n_25));
  MUX2X1 g188(.A (n_23), .B (out[4]), .S (en), .Y (n_24));
  DFFSR \out_reg[3] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_37));
  HAX1 g190(.A (out[4]), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g191(.A (n_20), .Y (n_21));
  MUX2X1 g192(.A (n_19), .B (out[3]), .S (en), .Y (n_20));
  DFFSR \out_reg[2] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_38));
  HAX1 g194(.A (out[3]), .B (n_14), .YC (n_18), .YS (n_19));
  INVX1 g195(.A (n_16), .Y (n_17));
  MUX2X1 g196(.A (n_15), .B (out[2]), .S (en), .Y (n_16));
  DFFSR \out_reg[1] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_39));
  HAX1 g198(.A (out[2]), .B (n_10), .YC (n_14), .YS (n_15));
  INVX1 g199(.A (n_12), .Y (n_13));
  MUX2X1 g200(.A (n_11), .B (out[1]), .S (en), .Y (n_12));
  DFFSR \out_reg[0] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_40));
  HAX1 g202(.A (out[1]), .B (out[0]), .YC (n_10), .YS (n_11));
  INVX1 g216(.A (rst), .Y (n_9));
  BUFX2 drc_bufs245(.A (n_40), .Y (out[0]));
  BUFX2 drc_bufs247(.A (n_35), .Y (out[5]));
  BUFX2 drc_bufs248(.A (n_36), .Y (out[4]));
  BUFX2 drc_bufs249(.A (n_37), .Y (out[3]));
  BUFX2 drc_bufs250(.A (n_38), .Y (out[2]));
  BUFX2 drc_bufs251(.A (n_39), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_6b_quad_2(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire [5:0] ctr4_out;
  comp_6b_8 comp6_a(.a_gt_b (sn_out_a), .a (bin_in_a), .b (ctr4_out));
  comp_6b_9 comp6_b(.a_gt_b (sn_out_b), .a (bin_in_b), .b (ctr4_out));
  comp_6b_10 comp6_c(.a_gt_b (sn_out_c), .a (bin_in_c), .b (ctr4_out));
  comp_6b_11 comp6_d(.a_gt_b (sn_out_d), .a (bin_in_d), .b (ctr4_out));
  counter_WIDTH6_2 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module prg_6b_4in_highmid(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out, ctr_overflow;
  wire n_0, n_1, n_2, n_3, n_4, n_5, sn_out_a, sn_out_b;
  wire sn_out_c, sn_out_d;
  prg_6b_quad_2 prg_ab(.clk (clk), .rst (rst), .en (en), .bin_in_a
       (bin_in_a), .bin_in_b (bin_in_b), .bin_in_c (bin_in_c),
       .bin_in_d (bin_in_d), .sn_out_a (sn_out_a), .sn_out_b
       (sn_out_b), .sn_out_c (sn_out_c), .sn_out_d (sn_out_d),
       .ctr_overflow (ctr_overflow));
  OAI21X1 g67(.A (n_0), .B (n_1), .C (n_5), .Y (sn_out));
  OAI21X1 g68(.A (sn_out_b), .B (sn_out_a), .C (n_2), .Y (n_5));
  NOR2X1 g69(.A (sn_out_c), .B (sn_out_d), .Y (n_4));
  NAND2X1 g70(.A (sn_out_b), .B (sn_out_a), .Y (n_3));
  AND2X1 g71(.A (sn_out_d), .B (sn_out_c), .Y (n_2));
  BUFX2 drc_bufs(.A (n_4), .Y (n_1));
  BUFX2 drc_bufs72(.A (n_3), .Y (n_0));
endmodule

module comp_1b_72(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_73(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_74(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_75(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_76(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_77(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_12(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED12, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_72 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED12),
       .a_larger (agt_28));
  comp_1b_73 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_74 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_75 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_76 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_77 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_78(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_79(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_80(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_81(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_82(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_83(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_13(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED13, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_78 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED13),
       .a_larger (agt_28));
  comp_1b_79 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_80 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_81 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_82 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_83 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_84(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_85(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_86(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_87(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_88(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_89(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_14(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED14, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_84 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED14),
       .a_larger (agt_28));
  comp_1b_85 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_86 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_87 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_88 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_89 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g18(.A (e_14), .Y (n_11));
  INVX1 g19(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module comp_1b_90(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_91(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_92(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_93(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_94(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_95(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_6b_15(a_gt_b, a, b);
  input [5:0] a, b;
  output a_gt_b;
  wire [5:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED15, agt, agt_17, agt_19, agt_22, agt_25, agt_28, e;
  wire e_13, e_14, e_15, e_16, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  comp_1b_90 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED15),
       .a_larger (agt_28));
  comp_1b_91 comp1(.a (a[1]), .b (b[1]), .equal (e_16), .a_larger
       (agt_25));
  comp_1b_92 comp2(.a (a[2]), .b (b[2]), .equal (e_15), .a_larger
       (agt_22));
  comp_1b_93 comp3(.a (a[3]), .b (b[3]), .equal (e_14), .a_larger
       (agt_19));
  comp_1b_94 comp4(.a (a[4]), .b (b[4]), .equal (e_13), .a_larger
       (agt));
  comp_1b_95 comp5(.a (a[5]), .b (b[5]), .equal (e), .a_larger
       (agt_17));
  INVX1 g19(.A (e_14), .Y (n_11));
  INVX1 g18(.A (e), .Y (n_10));
  OAI21X1 g141(.A (n_10), .B (n_2), .C (n_4), .Y (a_gt_b));
  AOI21X1 g142(.A (e_13), .B (n_8), .C (agt), .Y (n_9));
  OAI21X1 g143(.A (n_11), .B (n_1), .C (n_3), .Y (n_8));
  AOI21X1 g144(.A (e_15), .B (n_6), .C (agt_22), .Y (n_7));
  INVX1 g145(.A (n_0), .Y (n_6));
  AOI21X1 g146(.A (agt_28), .B (e_16), .C (agt_25), .Y (n_5));
  INVX1 g147(.A (agt_17), .Y (n_4));
  INVX1 g148(.A (agt_19), .Y (n_3));
  BUFX2 drc_bufs(.A (n_9), .Y (n_2));
  BUFX2 drc_bufs149(.A (n_7), .Y (n_1));
  BUFX2 drc_bufs150(.A (n_5), .Y (n_0));
endmodule

module counter_WIDTH6_3(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [5:0] out;
  output overflow;
  wire clk, en, rst;
  wire [5:0] out;
  wire overflow;
  wire n_0, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_33, n_35, n_36, n_37, n_38, n_39, n_40;
  DFFSR \out_reg[5] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_35));
  DFFSR overflow_reg(.R (n_9), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_33));
  INVX1 g181(.A (n_30), .Y (n_31));
  MUX2X1 g182(.A (n_26), .B (overflow), .S (en), .Y (n_30));
  INVX1 g183(.A (n_28), .Y (n_29));
  MUX2X1 g184(.A (n_27), .B (out[5]), .S (en), .Y (n_28));
  DFFSR \out_reg[4] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_36));
  HAX1 g186(.A (out[5]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g187(.A (n_24), .Y (n_25));
  MUX2X1 g188(.A (n_23), .B (out[4]), .S (en), .Y (n_24));
  DFFSR \out_reg[3] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_37));
  HAX1 g190(.A (out[4]), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g191(.A (n_20), .Y (n_21));
  MUX2X1 g192(.A (n_19), .B (out[3]), .S (en), .Y (n_20));
  DFFSR \out_reg[2] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_38));
  HAX1 g194(.A (out[3]), .B (n_14), .YC (n_18), .YS (n_19));
  INVX1 g195(.A (n_16), .Y (n_17));
  MUX2X1 g196(.A (n_15), .B (out[2]), .S (en), .Y (n_16));
  DFFSR \out_reg[1] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_39));
  HAX1 g198(.A (out[2]), .B (n_10), .YC (n_14), .YS (n_15));
  INVX1 g199(.A (n_12), .Y (n_13));
  MUX2X1 g200(.A (n_11), .B (out[1]), .S (en), .Y (n_12));
  DFFSR \out_reg[0] (.R (n_9), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_40));
  HAX1 g202(.A (out[1]), .B (out[0]), .YC (n_10), .YS (n_11));
  INVX1 g216(.A (rst), .Y (n_9));
  BUFX2 drc_bufs245(.A (n_40), .Y (out[0]));
  BUFX2 drc_bufs246(.A (n_33), .Y (overflow));
  BUFX2 drc_bufs247(.A (n_35), .Y (out[5]));
  BUFX2 drc_bufs248(.A (n_36), .Y (out[4]));
  BUFX2 drc_bufs249(.A (n_37), .Y (out[3]));
  BUFX2 drc_bufs250(.A (n_38), .Y (out[2]));
  BUFX2 drc_bufs251(.A (n_39), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_6b_quad_3(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out_a, sn_out_b, sn_out_c, sn_out_d, ctr_overflow;
  wire [5:0] ctr4_out;
  comp_6b_12 comp6_a(.a_gt_b (sn_out_a), .a (bin_in_a), .b (ctr4_out));
  comp_6b_13 comp6_b(.a_gt_b (sn_out_b), .a (bin_in_b), .b (ctr4_out));
  comp_6b_14 comp6_c(.a_gt_b (sn_out_c), .a (bin_in_c), .b (ctr4_out));
  comp_6b_15 comp6_d(.a_gt_b (sn_out_d), .a (bin_in_d), .b (ctr4_out));
  counter_WIDTH6_3 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module prg_6b_4in_min(clk, rst, en, bin_in_a, bin_in_b, bin_in_c,
     bin_in_d, sn_out, ctr_overflow);
  input clk, rst, en;
  input [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [5:0] bin_in_a, bin_in_b, bin_in_c, bin_in_d;
  wire sn_out, ctr_overflow;
  wire n_0, n_1, n_2, sn_out_a, sn_out_b, sn_out_c, sn_out_d;
  prg_6b_quad_3 prg_ab(.clk (clk), .rst (rst), .en (en), .bin_in_a
       (bin_in_a), .bin_in_b (bin_in_b), .bin_in_c (bin_in_c),
       .bin_in_d (bin_in_d), .sn_out_a (sn_out_a), .sn_out_b
       (sn_out_b), .sn_out_c (sn_out_c), .sn_out_d (sn_out_d),
       .ctr_overflow (ctr_overflow));
  INVX1 g23(.A (n_0), .Y (sn_out));
  NAND3X1 g24(.A (sn_out_c), .B (sn_out_d), .C (n_1), .Y (n_2));
  AND2X1 g25(.A (sn_out_b), .B (sn_out_a), .Y (n_1));
  BUFX2 drc_bufs(.A (n_2), .Y (n_0));
endmodule

module increment_unsigned(A, CI, Z);
  input [23:0] A;
  input CI;
  output [23:0] Z;
  wire [23:0] A;
  wire CI;
  wire [23:0] Z;
  wire n_1, n_3, n_5, n_7, n_9, n_11, n_13, n_15;
  wire n_17, n_19, n_21, n_23, n_25, n_27, n_29, n_31;
  wire n_33, n_35, n_37, n_39, n_41, n_43;
  XOR2X1 g161(.A (n_43), .B (A[23]), .Y (Z[23]));
  HAX1 g162(.A (A[22]), .B (n_41), .YC (n_43), .YS (Z[22]));
  HAX1 g163(.A (A[21]), .B (n_39), .YC (n_41), .YS (Z[21]));
  HAX1 g164(.A (A[20]), .B (n_37), .YC (n_39), .YS (Z[20]));
  HAX1 g165(.A (A[19]), .B (n_35), .YC (n_37), .YS (Z[19]));
  HAX1 g166(.A (A[18]), .B (n_33), .YC (n_35), .YS (Z[18]));
  HAX1 g167(.A (A[17]), .B (n_31), .YC (n_33), .YS (Z[17]));
  HAX1 g168(.A (A[16]), .B (n_29), .YC (n_31), .YS (Z[16]));
  HAX1 g169(.A (A[15]), .B (n_27), .YC (n_29), .YS (Z[15]));
  HAX1 g170(.A (A[14]), .B (n_25), .YC (n_27), .YS (Z[14]));
  HAX1 g171(.A (A[13]), .B (n_23), .YC (n_25), .YS (Z[13]));
  HAX1 g172(.A (A[12]), .B (n_21), .YC (n_23), .YS (Z[12]));
  HAX1 g173(.A (A[11]), .B (n_19), .YC (n_21), .YS (Z[11]));
  HAX1 g174(.A (A[10]), .B (n_17), .YC (n_19), .YS (Z[10]));
  HAX1 g175(.A (A[9]), .B (n_15), .YC (n_17), .YS (Z[9]));
  HAX1 g176(.A (A[8]), .B (n_13), .YC (n_15), .YS (Z[8]));
  HAX1 g177(.A (A[7]), .B (n_11), .YC (n_13), .YS (Z[7]));
  HAX1 g178(.A (A[6]), .B (n_9), .YC (n_11), .YS (Z[6]));
  HAX1 g179(.A (A[5]), .B (n_7), .YC (n_9), .YS (Z[5]));
  HAX1 g180(.A (A[4]), .B (n_5), .YC (n_7), .YS (Z[4]));
  HAX1 g181(.A (A[3]), .B (n_3), .YC (n_5), .YS (Z[3]));
  HAX1 g182(.A (A[2]), .B (n_1), .YC (n_3), .YS (Z[2]));
  HAX1 g183(.A (A[0]), .B (A[1]), .YC (n_1), .YS (Z[1]));
endmodule

module counter_WIDTH24(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [23:0] out;
  output overflow;
  wire clk, en, rst;
  wire [23:0] out;
  wire overflow;
  wire UNCONNECTED16, n_0, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_74, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  increment_unsigned inc_add_36_16_1(.A (out), .CI (1'b1), .Z ({n_96,
       n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105,
       n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114,
       n_115, n_116, n_117, n_118, UNCONNECTED16}));
  INVX1 g44(.A (rst), .Y (n_74));
  DFFSR \out_reg[10] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_58));
  DFFSR \out_reg[12] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_46), .Q
       (n_60));
  DFFSR \out_reg[13] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_44), .Q
       (n_61));
  DFFSR \out_reg[5] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_47), .Q
       (n_53));
  DFFSR \out_reg[6] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_45), .Q
       (n_54));
  DFFSR \out_reg[7] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_43), .Q
       (n_55));
  DFFSR \out_reg[8] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_42), .Q
       (n_56));
  DFFSR \out_reg[14] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_41), .Q
       (n_62));
  DFFSR \out_reg[9] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_40), .Q
       (n_57));
  DFFSR \out_reg[15] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_39), .Q
       (n_63));
  DFFSR \out_reg[16] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_38), .Q
       (n_64));
  DFFSR \out_reg[17] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_37), .Q
       (n_65));
  DFFSR \out_reg[18] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_36), .Q
       (n_66));
  DFFSR \out_reg[19] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_23), .Q
       (n_67));
  DFFSR \out_reg[11] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_59));
  DFFSR \out_reg[1] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_22), .Q
       (n_49));
  DFFSR \out_reg[20] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_68));
  DFFSR \out_reg[21] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_20), .Q
       (n_69));
  DFFSR \out_reg[22] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_70));
  DFFSR \out_reg[23] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_71));
  DFFSR \out_reg[2] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_50));
  DFFSR \out_reg[3] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_51));
  DFFSR \out_reg[4] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_52));
  DFFSR \out_reg[0] (.R (n_74), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_48));
  INVX1 g68(.A (n_35), .Y (n_47));
  INVX1 g69(.A (n_34), .Y (n_46));
  INVX1 g70(.A (n_33), .Y (n_45));
  INVX1 g71(.A (n_32), .Y (n_44));
  INVX1 g72(.A (n_31), .Y (n_43));
  INVX1 g73(.A (n_30), .Y (n_42));
  INVX1 g74(.A (n_29), .Y (n_41));
  INVX1 g75(.A (n_28), .Y (n_40));
  INVX1 g76(.A (n_27), .Y (n_39));
  INVX1 g77(.A (n_26), .Y (n_38));
  INVX1 g78(.A (n_25), .Y (n_37));
  INVX1 g79(.A (n_24), .Y (n_36));
  MUX2X1 g80(.A (n_114), .B (out[5]), .S (en), .Y (n_35));
  MUX2X1 g81(.A (n_107), .B (out[12]), .S (en), .Y (n_34));
  MUX2X1 g82(.A (n_113), .B (out[6]), .S (en), .Y (n_33));
  MUX2X1 g83(.A (n_106), .B (out[13]), .S (en), .Y (n_32));
  MUX2X1 g84(.A (n_112), .B (out[7]), .S (en), .Y (n_31));
  MUX2X1 g85(.A (n_111), .B (out[8]), .S (en), .Y (n_30));
  MUX2X1 g86(.A (n_105), .B (out[14]), .S (en), .Y (n_29));
  MUX2X1 g87(.A (n_110), .B (out[9]), .S (en), .Y (n_28));
  MUX2X1 g88(.A (n_104), .B (out[15]), .S (en), .Y (n_27));
  MUX2X1 g89(.A (n_103), .B (out[16]), .S (en), .Y (n_26));
  MUX2X1 g90(.A (n_102), .B (out[17]), .S (en), .Y (n_25));
  MUX2X1 g91(.A (n_101), .B (out[18]), .S (en), .Y (n_24));
  INVX1 g92(.A (n_12), .Y (n_23));
  INVX1 g93(.A (n_11), .Y (n_22));
  INVX1 g94(.A (n_10), .Y (n_21));
  INVX1 g95(.A (n_9), .Y (n_20));
  INVX1 g96(.A (n_8), .Y (n_19));
  INVX1 g97(.A (n_7), .Y (n_18));
  INVX1 g98(.A (n_6), .Y (n_17));
  INVX1 g99(.A (n_5), .Y (n_16));
  INVX1 g100(.A (n_4), .Y (n_15));
  INVX1 g101(.A (n_3), .Y (n_14));
  INVX1 g102(.A (n_2), .Y (n_13));
  MUX2X1 g103(.A (n_100), .B (out[19]), .S (en), .Y (n_12));
  MUX2X1 g104(.A (n_118), .B (out[1]), .S (en), .Y (n_11));
  MUX2X1 g105(.A (n_99), .B (out[20]), .S (en), .Y (n_10));
  MUX2X1 g106(.A (n_98), .B (out[21]), .S (en), .Y (n_9));
  MUX2X1 g107(.A (n_97), .B (out[22]), .S (en), .Y (n_8));
  MUX2X1 g108(.A (n_96), .B (out[23]), .S (en), .Y (n_7));
  MUX2X1 g109(.A (n_117), .B (out[2]), .S (en), .Y (n_6));
  MUX2X1 g110(.A (n_109), .B (out[10]), .S (en), .Y (n_5));
  MUX2X1 g111(.A (n_116), .B (out[3]), .S (en), .Y (n_4));
  MUX2X1 g112(.A (n_115), .B (out[4]), .S (en), .Y (n_3));
  MUX2X1 g113(.A (n_108), .B (out[11]), .S (en), .Y (n_2));
  BUFX2 drc_bufs212(.A (n_71), .Y (out[23]));
  BUFX2 drc_bufs213(.A (n_48), .Y (out[0]));
  BUFX2 drc_bufs214(.A (n_49), .Y (out[1]));
  BUFX2 drc_bufs215(.A (n_50), .Y (out[2]));
  BUFX2 drc_bufs216(.A (n_51), .Y (out[3]));
  BUFX2 drc_bufs217(.A (n_52), .Y (out[4]));
  BUFX2 drc_bufs218(.A (n_53), .Y (out[5]));
  BUFX2 drc_bufs219(.A (n_54), .Y (out[6]));
  BUFX2 drc_bufs220(.A (n_55), .Y (out[7]));
  BUFX2 drc_bufs221(.A (n_56), .Y (out[8]));
  BUFX2 drc_bufs222(.A (n_57), .Y (out[9]));
  BUFX2 drc_bufs223(.A (n_58), .Y (out[10]));
  BUFX2 drc_bufs224(.A (n_59), .Y (out[11]));
  BUFX2 drc_bufs225(.A (n_60), .Y (out[12]));
  BUFX2 drc_bufs226(.A (n_61), .Y (out[13]));
  BUFX2 drc_bufs227(.A (n_62), .Y (out[14]));
  BUFX2 drc_bufs228(.A (n_63), .Y (out[15]));
  BUFX2 drc_bufs229(.A (n_64), .Y (out[16]));
  BUFX2 drc_bufs230(.A (n_65), .Y (out[17]));
  BUFX2 drc_bufs231(.A (n_66), .Y (out[18]));
  BUFX2 drc_bufs232(.A (n_67), .Y (out[19]));
  BUFX2 drc_bufs233(.A (n_68), .Y (out[20]));
  BUFX2 drc_bufs234(.A (n_69), .Y (out[21]));
  BUFX2 drc_bufs235(.A (n_70), .Y (out[22]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module dsc_mul(a, b, c, d, z, clk, rst, en, ov);
  input [5:0] a, b, c, d;
  input clk, rst, en;
  output [23:0] z;
  output ov;
  wire [5:0] a, b, c, d;
  wire clk, rst, en;
  wire [23:0] z;
  wire ov;
  wire ctr_ov_a, ctr_ov_b, ctr_ov_c, ctr_ov_d, dummy_ov, n_0, n_1, n_2;
  wire n_3, sn_out_a, sn_out_b, sn_out_c, sn_out_d, sn_out_mul;
  prg_6b_4in_max prg_a(.clk (clk), .rst (rst), .en (en), .bin_in_a (a),
       .bin_in_b (b), .bin_in_c (c), .bin_in_d (d), .sn_out (sn_out_a),
       .ctr_overflow (ctr_ov_a));
  prg_6b_4in_lowmid prg_b(.clk (ctr_ov_a), .rst (rst), .en (en),
       .bin_in_a (a), .bin_in_b (b), .bin_in_c (c), .bin_in_d (d),
       .sn_out (sn_out_b), .ctr_overflow (ctr_ov_b));
  prg_6b_4in_highmid prg_c(.clk (ctr_ov_b), .rst (rst), .en (en),
       .bin_in_a (a), .bin_in_b (b), .bin_in_c (c), .bin_in_d (d),
       .sn_out (sn_out_c), .ctr_overflow (ctr_ov_c));
  prg_6b_4in_min prg_d(.clk (ctr_ov_c), .rst (rst), .en (en), .bin_in_a
       (a), .bin_in_b (b), .bin_in_c (c), .bin_in_d (d), .sn_out
       (sn_out_d), .ctr_overflow (ctr_ov_d));
  counter_WIDTH24 stoch2bin_out(.out (z), .clk (clk), .en (sn_out_mul),
       .rst (rst), .overflow (dummy_ov));
  AND2X1 g28(.A (sn_out_b), .B (n_3), .Y (sn_out_mul));
  INVX1 g29(.A (n_0), .Y (n_3));
  NAND3X1 g30(.A (sn_out_d), .B (sn_out_c), .C (sn_out_a), .Y (n_2));
  OR2X1 g31(.A (ctr_ov_d), .B (n_1), .Y (ov));
  INVX1 g32(.A (sn_out_d), .Y (n_1));
  BUFX2 drc_bufs(.A (n_2), .Y (n_0));
endmodule

