
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mul 

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_3(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_16));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_3 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g12(.A (e), .Y (n_6));
  OAI21X1 g71(.A (n_6), .B (n_1), .C (n_2), .Y (a_gt_b));
  AOI21X1 g72(.A (e_13), .B (n_4), .C (agt), .Y (n_5));
  INVX1 g73(.A (n_0), .Y (n_4));
  AOI21X1 g74(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_3));
  INVX1 g75(.A (agt_9), .Y (n_2));
  BUFX2 drc_bufs(.A (n_5), .Y (n_1));
  BUFX2 drc_bufs76(.A (n_3), .Y (n_0));
endmodule

module counter_WIDTH4(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_26, n_27, n_28, n_29;
  DFFSR \out_reg[3] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_26));
  DFFSR overflow_reg(.R (n_7), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (overflow));
  INVX1 g65(.A (n_20), .Y (n_21));
  MUX2X1 g66(.A (n_16), .B (overflow), .S (en), .Y (n_20));
  INVX1 g67(.A (n_18), .Y (n_19));
  MUX2X1 g68(.A (n_17), .B (out[3]), .S (en), .Y (n_18));
  DFFSR \out_reg[2] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_27));
  HAX1 g70(.A (out[3]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g71(.A (n_14), .Y (n_15));
  MUX2X1 g72(.A (n_13), .B (out[2]), .S (en), .Y (n_14));
  DFFSR \out_reg[1] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_28));
  HAX1 g74(.A (out[2]), .B (n_8), .YC (n_12), .YS (n_13));
  INVX1 g75(.A (n_10), .Y (n_11));
  MUX2X1 g76(.A (n_9), .B (out[1]), .S (en), .Y (n_10));
  DFFSR \out_reg[0] (.R (n_7), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_29));
  HAX1 g78(.A (out[1]), .B (out[0]), .YC (n_8), .YS (n_9));
  INVX1 g89(.A (rst), .Y (n_7));
  BUFX2 drc_bufs109(.A (n_29), .Y (out[0]));
  BUFX2 drc_bufs111(.A (n_26), .Y (out[3]));
  BUFX2 drc_bufs112(.A (n_27), .Y (out[2]));
  BUFX2 drc_bufs113(.A (n_28), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_4b(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  comp_4b comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module comp_1b_4(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_5(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_6(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_7(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b_1(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED0, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b_4 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED0),
       .a_larger (agt_16));
  comp_1b_5 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_6 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger (agt));
  comp_1b_7 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g12(.A (e), .Y (n_6));
  OAI21X1 g71(.A (n_6), .B (n_1), .C (n_2), .Y (a_gt_b));
  AOI21X1 g72(.A (e_13), .B (n_4), .C (agt), .Y (n_5));
  INVX1 g73(.A (n_0), .Y (n_4));
  AOI21X1 g74(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_3));
  INVX1 g75(.A (agt_9), .Y (n_2));
  BUFX2 drc_bufs(.A (n_5), .Y (n_1));
  BUFX2 drc_bufs76(.A (n_3), .Y (n_0));
endmodule

module counter_WIDTH4_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_1, n_3, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_20, n_21, n_27, n_28;
  wire n_29, n_30, n_31, n_32;
  DFFSR \out_reg[3] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_32), .Q
       (n_27));
  DFFSR \out_reg[2] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_28));
  INVX1 g108(.A (n_20), .Y (n_21));
  MUX2X1 g109(.A (n_17), .B (out[2]), .S (en), .Y (n_20));
  DFFSR overflow_reg(.R (n_10), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (overflow));
  DFFSR \out_reg[1] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_29));
  MUX2X1 g113(.A (n_1), .B (n_3), .S (en), .Y (n_18));
  HAX1 g114(.A (out[2]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g115(.A (n_14), .Y (n_15));
  MUX2X1 g116(.A (n_11), .B (out[1]), .S (en), .Y (n_14));
  NAND3X1 g117(.A (out[2]), .B (out[3]), .C (n_12), .Y (n_13));
  DFFSR \out_reg[0] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_30));
  HAX1 g119(.A (out[1]), .B (out[0]), .YC (n_12), .YS (n_11));
  INVX1 g135(.A (rst), .Y (n_10));
  INVX1 drc_bufs153(.A (overflow), .Y (n_3));
  BUFX2 drc_bufs155(.A (n_13), .Y (n_1));
  BUFX2 drc_bufs156(.A (n_30), .Y (out[0]));
  BUFX2 drc_bufs157(.A (n_29), .Y (out[1]));
  BUFX2 drc_bufs159(.A (n_27), .Y (out[3]));
  BUFX2 drc_bufs160(.A (n_28), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g167(.A (n_31), .B (out[3]), .Y (n_32));
  AND2X1 g3(.A (n_16), .B (en), .Y (n_31));
endmodule

module prg_4b_1(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  comp_4b_1 comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4_1 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module comp_1b_8(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_9(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_10(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_11(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_4b_2(a_gt_b, a, b);
  input [3:0] a, b;
  output a_gt_b;
  wire [3:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED1, agt, agt_9, agt_11, agt_16, e, e_13, e_19;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  comp_1b_8 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED1),
       .a_larger (agt_16));
  comp_1b_9 comp1(.a (a[1]), .b (b[1]), .equal (e_19), .a_larger
       (agt_11));
  comp_1b_10 comp2(.a (a[2]), .b (b[2]), .equal (e_13), .a_larger
       (agt));
  comp_1b_11 comp3(.a (a[3]), .b (b[3]), .equal (e), .a_larger (agt_9));
  INVX1 g12(.A (e), .Y (n_6));
  OAI21X1 g71(.A (n_6), .B (n_1), .C (n_2), .Y (a_gt_b));
  AOI21X1 g72(.A (e_13), .B (n_4), .C (agt), .Y (n_5));
  INVX1 g73(.A (n_0), .Y (n_4));
  AOI21X1 g74(.A (agt_16), .B (e_19), .C (agt_11), .Y (n_3));
  INVX1 g75(.A (agt_9), .Y (n_2));
  BUFX2 drc_bufs(.A (n_5), .Y (n_1));
  BUFX2 drc_bufs76(.A (n_3), .Y (n_0));
endmodule

module counter_WIDTH4_2(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [3:0] out;
  output overflow;
  wire clk, en, rst;
  wire [3:0] out;
  wire overflow;
  wire n_0, n_1, n_3, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_20, n_21, n_25, n_27;
  wire n_28, n_29, n_30, n_31, n_32;
  DFFSR \out_reg[3] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_32), .Q
       (n_27));
  DFFSR \out_reg[2] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_28));
  INVX1 g108(.A (n_20), .Y (n_21));
  MUX2X1 g109(.A (n_17), .B (out[2]), .S (en), .Y (n_20));
  DFFSR overflow_reg(.R (n_10), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_25));
  DFFSR \out_reg[1] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_29));
  MUX2X1 g113(.A (n_1), .B (n_3), .S (en), .Y (n_18));
  HAX1 g114(.A (out[2]), .B (n_12), .YC (n_16), .YS (n_17));
  INVX1 g115(.A (n_14), .Y (n_15));
  MUX2X1 g116(.A (n_11), .B (out[1]), .S (en), .Y (n_14));
  NAND3X1 g117(.A (out[2]), .B (out[3]), .C (n_12), .Y (n_13));
  DFFSR \out_reg[0] (.R (n_10), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_30));
  HAX1 g119(.A (out[1]), .B (out[0]), .YC (n_12), .YS (n_11));
  INVX1 g135(.A (rst), .Y (n_10));
  INVX1 drc_bufs137(.A (overflow), .Y (n_3));
  BUFX2 drc_bufs155(.A (n_13), .Y (n_1));
  BUFX2 drc_bufs156(.A (n_30), .Y (out[0]));
  BUFX2 drc_bufs157(.A (n_29), .Y (out[1]));
  BUFX2 drc_bufs158(.A (n_25), .Y (overflow));
  BUFX2 drc_bufs159(.A (n_27), .Y (out[3]));
  BUFX2 drc_bufs160(.A (n_28), .Y (out[2]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g167(.A (n_31), .B (out[3]), .Y (n_32));
  AND2X1 g3(.A (n_16), .B (en), .Y (n_31));
endmodule

module prg_4b_2(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  comp_4b_2 comp4(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH4_2 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module counter_WIDTH12(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [11:0] out;
  output overflow;
  wire clk, en, rst;
  wire [11:0] out;
  wire overflow;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_41;
  wire n_42, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_58, n_74, n_75;
  INVX1 g50(.A (rst), .Y (n_58));
  DFFSR \out_reg[11] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_75), .Q
       (n_56));
  DFFSR \out_reg[10] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_42), .Q
       (n_55));
  INVX1 g203(.A (n_41), .Y (n_42));
  MUX2X1 g204(.A (n_39), .B (out[10]), .S (en), .Y (n_41));
  DFFSR \out_reg[9] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_37), .Q
       (n_54));
  HAX1 g207(.A (out[10]), .B (n_34), .YC (n_38), .YS (n_39));
  INVX1 g208(.A (n_36), .Y (n_37));
  MUX2X1 g209(.A (n_35), .B (out[9]), .S (en), .Y (n_36));
  DFFSR \out_reg[8] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_53));
  HAX1 g211(.A (out[9]), .B (n_30), .YC (n_34), .YS (n_35));
  INVX1 g212(.A (n_32), .Y (n_33));
  MUX2X1 g213(.A (n_31), .B (out[8]), .S (en), .Y (n_32));
  DFFSR \out_reg[7] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_52));
  HAX1 g215(.A (out[8]), .B (n_26), .YC (n_30), .YS (n_31));
  INVX1 g216(.A (n_28), .Y (n_29));
  MUX2X1 g217(.A (n_27), .B (out[7]), .S (en), .Y (n_28));
  DFFSR \out_reg[6] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_51));
  HAX1 g219(.A (out[7]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g220(.A (n_24), .Y (n_25));
  MUX2X1 g221(.A (n_23), .B (out[6]), .S (en), .Y (n_24));
  DFFSR \out_reg[5] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_50));
  HAX1 g223(.A (out[6]), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g224(.A (n_20), .Y (n_21));
  MUX2X1 g225(.A (n_19), .B (out[5]), .S (en), .Y (n_20));
  DFFSR \out_reg[4] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_49));
  HAX1 g227(.A (out[5]), .B (n_14), .YC (n_18), .YS (n_19));
  INVX1 g228(.A (n_16), .Y (n_17));
  MUX2X1 g229(.A (n_15), .B (out[4]), .S (en), .Y (n_16));
  DFFSR \out_reg[3] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_48));
  HAX1 g231(.A (out[4]), .B (n_10), .YC (n_14), .YS (n_15));
  INVX1 g232(.A (n_12), .Y (n_13));
  MUX2X1 g233(.A (n_11), .B (out[3]), .S (en), .Y (n_12));
  DFFSR \out_reg[2] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_9), .Q
       (n_47));
  HAX1 g235(.A (out[3]), .B (n_6), .YC (n_10), .YS (n_11));
  INVX1 g236(.A (n_8), .Y (n_9));
  MUX2X1 g237(.A (n_7), .B (out[2]), .S (en), .Y (n_8));
  DFFSR \out_reg[1] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_5), .Q
       (n_46));
  HAX1 g239(.A (out[2]), .B (n_2), .YC (n_6), .YS (n_7));
  INVX1 g240(.A (n_4), .Y (n_5));
  MUX2X1 g241(.A (n_3), .B (out[1]), .S (en), .Y (n_4));
  DFFSR \out_reg[0] (.R (n_58), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_45));
  HAX1 g243(.A (out[1]), .B (out[0]), .YC (n_2), .YS (n_3));
  BUFX2 drc_bufs317(.A (n_56), .Y (out[11]));
  BUFX2 drc_bufs318(.A (n_45), .Y (out[0]));
  BUFX2 drc_bufs319(.A (n_46), .Y (out[1]));
  BUFX2 drc_bufs320(.A (n_47), .Y (out[2]));
  BUFX2 drc_bufs321(.A (n_48), .Y (out[3]));
  BUFX2 drc_bufs322(.A (n_49), .Y (out[4]));
  BUFX2 drc_bufs323(.A (n_50), .Y (out[5]));
  BUFX2 drc_bufs324(.A (n_51), .Y (out[6]));
  BUFX2 drc_bufs325(.A (n_52), .Y (out[7]));
  BUFX2 drc_bufs326(.A (n_53), .Y (out[8]));
  BUFX2 drc_bufs327(.A (n_54), .Y (out[9]));
  BUFX2 drc_bufs328(.A (n_55), .Y (out[10]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
  XOR2X1 g341(.A (n_74), .B (out[11]), .Y (n_75));
  AND2X1 g3(.A (en), .B (n_38), .Y (n_74));
endmodule

module dsc_mul(a, b, c, z, clk, rst, en, ov);
  input [3:0] a, b, c;
  input clk, rst, en;
  output [11:0] z;
  output ov;
  wire [3:0] a, b, c;
  wire clk, rst, en;
  wire [11:0] z;
  wire ov;
  wire ctr_ov_a, ctr_ov_b, ctr_ov_c, dummy_ov, n_0, n_1, sn_out_a,
       sn_out_b;
  wire sn_out_c, sn_out_mul;
  prg_4b prg_a(.clk (clk), .rst (rst), .en (en), .bin_in (a), .sn_out
       (sn_out_a), .ctr_overflow (ctr_ov_a));
  prg_4b_1 prg_b(.clk (ctr_ov_a), .rst (rst), .en (en), .bin_in (b),
       .sn_out (sn_out_b), .ctr_overflow (ctr_ov_b));
  prg_4b_2 prg_c(.clk (ctr_ov_b), .rst (rst), .en (en), .bin_in (c),
       .sn_out (sn_out_c), .ctr_overflow (ctr_ov_c));
  counter_WIDTH12 stoch2bin_out(.out (z), .clk (clk), .en (sn_out_mul),
       .rst (rst), .overflow (dummy_ov));
  AND2X1 g27(.A (sn_out_c), .B (n_1), .Y (sn_out_mul));
  OR2X1 g28(.A (ctr_ov_c), .B (n_0), .Y (ov));
  AND2X1 g29(.A (sn_out_a), .B (sn_out_b), .Y (n_1));
  INVX1 g30(.A (sn_out_c), .Y (n_0));
endmodule

