
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mul 

module det_stoch_mul(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g8(.A (b), .B (a), .Y (y));
endmodule

module comp_1b(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_1(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_2(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_3(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_4(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_5(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_6(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_7(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_8(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_9(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_10b(a_gt_b, a, b);
  input [9:0] a, b;
  output a_gt_b;
  wire [9:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED, agt, agt_29, agt_31, agt_34, agt_37, agt_40, agt_43;
  wire agt_46, agt_49, agt_52, e, e_21, e_22, e_23, e_24;
  wire e_25, e_26, e_27, e_28, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21;
  comp_1b comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED), .a_larger
       (agt_52));
  comp_1b_1 comp1(.a (a[1]), .b (b[1]), .equal (e_28), .a_larger
       (agt_49));
  comp_1b_2 comp2(.a (a[2]), .b (b[2]), .equal (e_27), .a_larger
       (agt_46));
  comp_1b_3 comp3(.a (a[3]), .b (b[3]), .equal (e_26), .a_larger
       (agt_43));
  comp_1b_4 comp4(.a (a[4]), .b (b[4]), .equal (e_25), .a_larger
       (agt_40));
  comp_1b_5 comp5(.a (a[5]), .b (b[5]), .equal (e_24), .a_larger
       (agt_37));
  comp_1b_6 comp6(.a (a[6]), .b (b[6]), .equal (e_23), .a_larger
       (agt_34));
  comp_1b_7 comp7(.a (a[7]), .b (b[7]), .equal (e_22), .a_larger
       (agt_31));
  comp_1b_8 comp8(.a (a[8]), .b (b[8]), .equal (e_21), .a_larger (agt));
  comp_1b_9 comp9(.a (a[9]), .b (b[9]), .equal (e), .a_larger (agt_29));
  INVX1 g32(.A (e_26), .Y (n_21));
  INVX1 g35(.A (e_24), .Y (n_20));
  INVX1 g33(.A (e_22), .Y (n_19));
  INVX1 g34(.A (e), .Y (n_18));
  OAI21X1 g247(.A (n_18), .B (n_4), .C (n_5), .Y (a_gt_b));
  AOI21X1 g248(.A (e_21), .B (n_16), .C (agt), .Y (n_17));
  OAI21X1 g249(.A (n_19), .B (n_3), .C (n_8), .Y (n_16));
  AOI21X1 g250(.A (e_23), .B (n_14), .C (agt_34), .Y (n_15));
  OAI21X1 g251(.A (n_20), .B (n_1), .C (n_7), .Y (n_14));
  AOI21X1 g252(.A (e_25), .B (n_12), .C (agt_40), .Y (n_13));
  OAI21X1 g253(.A (n_21), .B (n_2), .C (n_6), .Y (n_12));
  AOI21X1 g254(.A (e_27), .B (n_10), .C (agt_46), .Y (n_11));
  INVX1 g255(.A (n_0), .Y (n_10));
  AOI21X1 g256(.A (agt_52), .B (e_28), .C (agt_49), .Y (n_9));
  INVX1 g257(.A (agt_31), .Y (n_8));
  INVX1 g258(.A (agt_37), .Y (n_7));
  INVX1 g259(.A (agt_43), .Y (n_6));
  INVX1 g260(.A (agt_29), .Y (n_5));
  BUFX2 drc_bufs(.A (n_17), .Y (n_4));
  BUFX2 drc_bufs261(.A (n_15), .Y (n_3));
  BUFX2 drc_bufs262(.A (n_11), .Y (n_2));
  BUFX2 drc_bufs263(.A (n_13), .Y (n_1));
  BUFX2 drc_bufs264(.A (n_9), .Y (n_0));
endmodule

module counter_WIDTH10(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [9:0] out;
  output overflow;
  wire clk, en, rst;
  wire [9:0] out;
  wire overflow;
  wire n_0, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63;
  DFFSR \out_reg[9] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_51), .Q
       (n_54));
  DFFSR overflow_reg(.R (n_13), .S (1'b1), .CLK (clk), .D (n_49), .Q
       (overflow));
  INVX1 g168(.A (n_50), .Y (n_51));
  MUX2X1 g169(.A (n_47), .B (out[9]), .S (en), .Y (n_50));
  INVX1 g170(.A (n_48), .Y (n_49));
  MUX2X1 g171(.A (n_46), .B (overflow), .S (en), .Y (n_48));
  DFFSR \out_reg[8] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_45), .Q
       (n_55));
  HAX1 g173(.A (out[9]), .B (n_42), .YC (n_46), .YS (n_47));
  INVX1 g174(.A (n_44), .Y (n_45));
  MUX2X1 g175(.A (n_43), .B (out[8]), .S (en), .Y (n_44));
  DFFSR \out_reg[7] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_41), .Q
       (n_56));
  HAX1 g177(.A (out[8]), .B (n_38), .YC (n_42), .YS (n_43));
  INVX1 g178(.A (n_40), .Y (n_41));
  MUX2X1 g179(.A (n_39), .B (out[7]), .S (en), .Y (n_40));
  DFFSR \out_reg[6] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_37), .Q
       (n_57));
  HAX1 g181(.A (out[7]), .B (n_34), .YC (n_38), .YS (n_39));
  INVX1 g182(.A (n_36), .Y (n_37));
  MUX2X1 g183(.A (n_35), .B (out[6]), .S (en), .Y (n_36));
  DFFSR \out_reg[5] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_58));
  HAX1 g185(.A (out[6]), .B (n_30), .YC (n_34), .YS (n_35));
  INVX1 g186(.A (n_32), .Y (n_33));
  MUX2X1 g187(.A (n_31), .B (out[5]), .S (en), .Y (n_32));
  DFFSR \out_reg[4] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_29), .Q
       (n_59));
  HAX1 g189(.A (out[5]), .B (n_26), .YC (n_30), .YS (n_31));
  INVX1 g190(.A (n_28), .Y (n_29));
  MUX2X1 g191(.A (n_27), .B (out[4]), .S (en), .Y (n_28));
  DFFSR \out_reg[3] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_25), .Q
       (n_60));
  HAX1 g193(.A (out[4]), .B (n_22), .YC (n_26), .YS (n_27));
  INVX1 g194(.A (n_24), .Y (n_25));
  MUX2X1 g195(.A (n_23), .B (out[3]), .S (en), .Y (n_24));
  DFFSR \out_reg[2] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_21), .Q
       (n_61));
  HAX1 g197(.A (out[3]), .B (n_18), .YC (n_22), .YS (n_23));
  INVX1 g198(.A (n_20), .Y (n_21));
  MUX2X1 g199(.A (n_19), .B (out[2]), .S (en), .Y (n_20));
  DFFSR \out_reg[1] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_62));
  HAX1 g201(.A (out[2]), .B (n_14), .YC (n_18), .YS (n_19));
  INVX1 g202(.A (n_16), .Y (n_17));
  MUX2X1 g203(.A (n_15), .B (out[1]), .S (en), .Y (n_16));
  DFFSR \out_reg[0] (.R (n_13), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_63));
  HAX1 g205(.A (out[1]), .B (out[0]), .YC (n_14), .YS (n_15));
  INVX1 g228(.A (rst), .Y (n_13));
  BUFX2 drc_bufs272(.A (n_63), .Y (out[0]));
  BUFX2 drc_bufs274(.A (n_54), .Y (out[9]));
  BUFX2 drc_bufs275(.A (n_55), .Y (out[8]));
  BUFX2 drc_bufs276(.A (n_56), .Y (out[7]));
  BUFX2 drc_bufs277(.A (n_57), .Y (out[6]));
  BUFX2 drc_bufs278(.A (n_58), .Y (out[5]));
  BUFX2 drc_bufs279(.A (n_59), .Y (out[4]));
  BUFX2 drc_bufs280(.A (n_60), .Y (out[3]));
  BUFX2 drc_bufs281(.A (n_61), .Y (out[2]));
  BUFX2 drc_bufs282(.A (n_62), .Y (out[1]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module prg_10b(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [9:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [9:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [9:0] ctr4_out;
  comp_10b comp10(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH10 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module comp_1b_10(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_1;
  AND2X1 g14(.A (n_1), .B (a), .Y (a_larger));
  INVX1 g15(.A (b), .Y (n_1));
endmodule

module comp_1b_11(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_12(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_13(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_14(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_15(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_16(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_17(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_18(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_1b_19(a, b, equal, a_larger);
  input a, b;
  output equal, a_larger;
  wire a, b;
  wire equal, a_larger;
  wire n_0;
  HAX1 g27(.A (a), .B (n_0), .YC (a_larger), .YS (equal));
  INVX1 g28(.A (b), .Y (n_0));
endmodule

module comp_10b_1(a_gt_b, a, b);
  input [9:0] a, b;
  output a_gt_b;
  wire [9:0] a, b;
  wire a_gt_b;
  wire UNCONNECTED0, agt, agt_29, agt_31, agt_34, agt_37, agt_40,
       agt_43;
  wire agt_46, agt_49, agt_52, e, e_21, e_22, e_23, e_24;
  wire e_25, e_26, e_27, e_28, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21;
  comp_1b_10 comp0(.a (a[0]), .b (b[0]), .equal (UNCONNECTED0),
       .a_larger (agt_52));
  comp_1b_11 comp1(.a (a[1]), .b (b[1]), .equal (e_28), .a_larger
       (agt_49));
  comp_1b_12 comp2(.a (a[2]), .b (b[2]), .equal (e_27), .a_larger
       (agt_46));
  comp_1b_13 comp3(.a (a[3]), .b (b[3]), .equal (e_26), .a_larger
       (agt_43));
  comp_1b_14 comp4(.a (a[4]), .b (b[4]), .equal (e_25), .a_larger
       (agt_40));
  comp_1b_15 comp5(.a (a[5]), .b (b[5]), .equal (e_24), .a_larger
       (agt_37));
  comp_1b_16 comp6(.a (a[6]), .b (b[6]), .equal (e_23), .a_larger
       (agt_34));
  comp_1b_17 comp7(.a (a[7]), .b (b[7]), .equal (e_22), .a_larger
       (agt_31));
  comp_1b_18 comp8(.a (a[8]), .b (b[8]), .equal (e_21), .a_larger
       (agt));
  comp_1b_19 comp9(.a (a[9]), .b (b[9]), .equal (e), .a_larger
       (agt_29));
  INVX1 g33(.A (e_26), .Y (n_21));
  INVX1 g32(.A (e_24), .Y (n_20));
  INVX1 g34(.A (e_22), .Y (n_19));
  INVX1 g35(.A (e), .Y (n_18));
  OAI21X1 g247(.A (n_18), .B (n_4), .C (n_5), .Y (a_gt_b));
  AOI21X1 g248(.A (e_21), .B (n_16), .C (agt), .Y (n_17));
  OAI21X1 g249(.A (n_19), .B (n_3), .C (n_8), .Y (n_16));
  AOI21X1 g250(.A (e_23), .B (n_14), .C (agt_34), .Y (n_15));
  OAI21X1 g251(.A (n_20), .B (n_1), .C (n_7), .Y (n_14));
  AOI21X1 g252(.A (e_25), .B (n_12), .C (agt_40), .Y (n_13));
  OAI21X1 g253(.A (n_21), .B (n_2), .C (n_6), .Y (n_12));
  AOI21X1 g254(.A (e_27), .B (n_10), .C (agt_46), .Y (n_11));
  INVX1 g255(.A (n_0), .Y (n_10));
  AOI21X1 g256(.A (agt_52), .B (e_28), .C (agt_49), .Y (n_9));
  INVX1 g257(.A (agt_31), .Y (n_8));
  INVX1 g258(.A (agt_37), .Y (n_7));
  INVX1 g259(.A (agt_43), .Y (n_6));
  INVX1 g260(.A (agt_29), .Y (n_5));
  BUFX2 drc_bufs(.A (n_17), .Y (n_4));
  BUFX2 drc_bufs261(.A (n_15), .Y (n_3));
  BUFX2 drc_bufs262(.A (n_11), .Y (n_2));
  BUFX2 drc_bufs263(.A (n_13), .Y (n_1));
  BUFX2 drc_bufs264(.A (n_9), .Y (n_0));
endmodule

module counter_WIDTH10_1(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [9:0] out;
  output overflow;
  wire clk, en, rst;
  wire [9:0] out;
  wire overflow;
  wire n_0, n_1, n_2, n_5, n_9, n_11, n_15, n_17;
  wire n_19, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_52, n_53;
  wire n_54, n_55, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_79, n_80;
  DFFSR \out_reg[7] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_64), .Q
       (n_69));
  MUX2X1 g375(.A (n_61), .B (n_11), .S (en), .Y (n_64));
  DFFSR \out_reg[6] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_63), .Q
       (n_70));
  INVX1 g377(.A (n_62), .Y (n_63));
  MUX2X1 g378(.A (n_60), .B (out[6]), .S (en), .Y (n_62));
  MUX2X1 g379(.A (n_11), .B (out[7]), .S (n_59), .Y (n_61));
  DFFSR \out_reg[5] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_58), .Q
       (n_71));
  DFFSR \out_reg[9] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_80), .Q
       (n_67));
  HAX1 g382(.A (out[6]), .B (n_54), .YC (n_59), .YS (n_60));
  INVX1 g383(.A (n_57), .Y (n_58));
  MUX2X1 g384(.A (n_55), .B (out[5]), .S (en), .Y (n_57));
  DFFSR \out_reg[8] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_53), .Q
       (n_68));
  HAX1 g387(.A (out[5]), .B (n_45), .YC (n_54), .YS (n_55));
  DFFSR \out_reg[4] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_50), .Q
       (n_72));
  INVX1 g389(.A (n_52), .Y (n_53));
  MUX2X1 g390(.A (n_48), .B (out[8]), .S (en), .Y (n_52));
  INVX1 g392(.A (n_49), .Y (n_50));
  MUX2X1 g393(.A (n_46), .B (out[4]), .S (en), .Y (n_49));
  HAX1 g394(.A (out[8]), .B (n_41), .YC (n_47), .YS (n_48));
  HAX1 g395(.A (out[4]), .B (n_39), .YC (n_45), .YS (n_46));
  DFFSR \out_reg[3] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_44), .Q
       (n_73));
  DFFSR overflow_reg(.R (n_22), .S (1'b1), .CLK (clk), .D (n_42), .Q
       (n_65));
  INVX1 g398(.A (n_43), .Y (n_44));
  MUX2X1 g399(.A (n_38), .B (out[3]), .S (en), .Y (n_43));
  OAI21X1 g400(.A (n_23), .B (n_1), .C (n_0), .Y (n_42));
  AND2X1 g401(.A (n_39), .B (n_29), .Y (n_41));
  DFFSR \out_reg[2] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_37), .Q
       (n_74));
  NAND3X1 g403(.A (out[0]), .B (out[8]), .C (n_35), .Y (n_40));
  HAX1 g404(.A (out[3]), .B (n_33), .YC (n_39), .YS (n_38));
  INVX1 g405(.A (n_36), .Y (n_37));
  MUX2X1 g406(.A (out[2]), .B (n_34), .S (n_23), .Y (n_36));
  NOR3X1 g407(.A (n_15), .B (n_9), .C (n_2), .Y (n_35));
  DFFSR \out_reg[1] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_75));
  HAX1 g409(.A (out[2]), .B (n_27), .YC (n_33), .YS (n_34));
  NAND3X1 g410(.A (out[1]), .B (out[9]), .C (n_29), .Y (n_32));
  INVX1 g411(.A (n_30), .Y (n_31));
  MUX2X1 g412(.A (out[1]), .B (n_28), .S (n_23), .Y (n_30));
  DFFSR \out_reg[0] (.R (n_22), .S (1'b1), .CLK (clk), .D (n_26), .Q
       (n_76));
  NOR3X1 g414(.A (n_17), .B (n_19), .C (n_24), .Y (n_29));
  HAX1 g415(.A (out[1]), .B (out[0]), .YC (n_27), .YS (n_28));
  MUX2X1 g416(.A (en), .B (n_23), .S (out[0]), .Y (n_26));
  NAND2X1 g417(.A (n_23), .B (overflow), .Y (n_25));
  OR2X1 g418(.A (n_5), .B (n_11), .Y (n_24));
  INVX1 g451(.A (en), .Y (n_23));
  INVX1 g452(.A (rst), .Y (n_22));
  INVX1 drc_bufs458(.A (out[7]), .Y (n_11));
  INVX1 drc_bufs466(.A (out[3]), .Y (n_15));
  INVX1 drc_bufs470(.A (out[4]), .Y (n_17));
  INVX1 drc_bufs486(.A (out[6]), .Y (n_5));
  INVX1 drc_bufs490(.A (out[5]), .Y (n_19));
  INVX1 drc_bufs494(.A (out[2]), .Y (n_9));
  BUFX2 drc_bufs496(.A (n_32), .Y (n_2));
  BUFX2 drc_bufs497(.A (n_40), .Y (n_1));
  BUFX2 drc_bufs498(.A (n_25), .Y (n_0));
  BUFX2 drc_bufs499(.A (n_76), .Y (out[0]));
  BUFX2 drc_bufs500(.A (n_75), .Y (out[1]));
  BUFX2 drc_bufs501(.A (n_73), .Y (out[3]));
  BUFX2 drc_bufs502(.A (n_69), .Y (out[7]));
  BUFX2 drc_bufs503(.A (n_65), .Y (overflow));
  BUFX2 drc_bufs504(.A (n_67), .Y (out[9]));
  BUFX2 drc_bufs505(.A (n_68), .Y (out[8]));
  BUFX2 drc_bufs506(.A (n_72), .Y (out[4]));
  BUFX2 drc_bufs507(.A (n_70), .Y (out[6]));
  BUFX2 drc_bufs508(.A (n_71), .Y (out[5]));
  BUFX2 drc_bufs509(.A (n_74), .Y (out[2]));
  XOR2X1 g2(.A (n_79), .B (out[9]), .Y (n_80));
  AND2X1 g3(.A (n_47), .B (en), .Y (n_79));
endmodule

module prg_10b_1(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [9:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [9:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [9:0] ctr4_out;
  comp_10b_1 comp10(.a_gt_b (sn_out), .a (bin_in), .b (ctr4_out));
  counter_WIDTH10_1 ctr4(.out (ctr4_out), .clk (clk), .en (en), .rst
       (rst), .overflow (ctr_overflow));
endmodule

module increment_unsigned_2(A, CI, Z);
  input [19:0] A;
  input CI;
  output [19:0] Z;
  wire [19:0] A;
  wire CI;
  wire [19:0] Z;
  wire n_1, n_3, n_5, n_7, n_9, n_11, n_13, n_15;
  wire n_17, n_19, n_21, n_23, n_25, n_27, n_29, n_31;
  wire n_33, n_35;
  XOR2X1 g133(.A (n_35), .B (A[19]), .Y (Z[19]));
  HAX1 g134(.A (A[18]), .B (n_33), .YC (n_35), .YS (Z[18]));
  HAX1 g135(.A (A[17]), .B (n_31), .YC (n_33), .YS (Z[17]));
  HAX1 g136(.A (A[16]), .B (n_29), .YC (n_31), .YS (Z[16]));
  HAX1 g137(.A (A[15]), .B (n_27), .YC (n_29), .YS (Z[15]));
  HAX1 g138(.A (A[14]), .B (n_25), .YC (n_27), .YS (Z[14]));
  HAX1 g139(.A (A[13]), .B (n_23), .YC (n_25), .YS (Z[13]));
  HAX1 g140(.A (A[12]), .B (n_21), .YC (n_23), .YS (Z[12]));
  HAX1 g141(.A (A[11]), .B (n_19), .YC (n_21), .YS (Z[11]));
  HAX1 g142(.A (A[10]), .B (n_17), .YC (n_19), .YS (Z[10]));
  HAX1 g143(.A (A[9]), .B (n_15), .YC (n_17), .YS (Z[9]));
  HAX1 g144(.A (A[8]), .B (n_13), .YC (n_15), .YS (Z[8]));
  HAX1 g145(.A (A[7]), .B (n_11), .YC (n_13), .YS (Z[7]));
  HAX1 g146(.A (A[6]), .B (n_9), .YC (n_11), .YS (Z[6]));
  HAX1 g147(.A (A[5]), .B (n_7), .YC (n_9), .YS (Z[5]));
  HAX1 g148(.A (A[4]), .B (n_5), .YC (n_7), .YS (Z[4]));
  HAX1 g149(.A (A[3]), .B (n_3), .YC (n_5), .YS (Z[3]));
  HAX1 g150(.A (A[2]), .B (n_1), .YC (n_3), .YS (Z[2]));
  HAX1 g151(.A (A[0]), .B (A[1]), .YC (n_1), .YS (Z[1]));
endmodule

module counter_WIDTH20(out, clk, en, rst, overflow);
  input clk, en, rst;
  output [19:0] out;
  output overflow;
  wire clk, en, rst;
  wire [19:0] out;
  wire overflow;
  wire UNCONNECTED1, n_0, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_62, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  increment_unsigned_2 inc_add_36_16_2(.A (out), .CI (1'b1), .Z ({n_84,
       n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94,
       n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102,
       UNCONNECTED1}));
  INVX1 g39(.A (rst), .Y (n_62));
  DFFSR \out_reg[10] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_19), .Q
       (n_50));
  DFFSR \out_reg[14] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_39), .Q
       (n_54));
  DFFSR \out_reg[15] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_38), .Q
       (n_55));
  DFFSR \out_reg[16] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_37), .Q
       (n_56));
  DFFSR \out_reg[17] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_36), .Q
       (n_57));
  DFFSR \out_reg[18] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_35), .Q
       (n_58));
  DFFSR \out_reg[19] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_34), .Q
       (n_59));
  DFFSR \out_reg[1] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_33), .Q
       (n_41));
  DFFSR \out_reg[2] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_32), .Q
       (n_42));
  DFFSR \out_reg[11] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_16), .Q
       (n_51));
  DFFSR \out_reg[3] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_31), .Q
       (n_43));
  DFFSR \out_reg[4] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_30), .Q
       (n_44));
  DFFSR \out_reg[5] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_18), .Q
       (n_45));
  DFFSR \out_reg[6] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_17), .Q
       (n_46));
  DFFSR \out_reg[12] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_15), .Q
       (n_52));
  DFFSR \out_reg[7] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_14), .Q
       (n_47));
  DFFSR \out_reg[8] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_13), .Q
       (n_48));
  DFFSR \out_reg[13] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_11), .Q
       (n_53));
  DFFSR \out_reg[9] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_12), .Q
       (n_49));
  DFFSR \out_reg[0] (.R (n_62), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_40));
  INVX1 g59(.A (n_29), .Y (n_39));
  INVX1 g60(.A (n_28), .Y (n_38));
  INVX1 g61(.A (n_27), .Y (n_37));
  INVX1 g62(.A (n_26), .Y (n_36));
  INVX1 g63(.A (n_25), .Y (n_35));
  INVX1 g64(.A (n_24), .Y (n_34));
  INVX1 g65(.A (n_23), .Y (n_33));
  INVX1 g66(.A (n_22), .Y (n_32));
  INVX1 g67(.A (n_21), .Y (n_31));
  INVX1 g68(.A (n_20), .Y (n_30));
  MUX2X1 g69(.A (n_89), .B (out[14]), .S (en), .Y (n_29));
  MUX2X1 g70(.A (n_88), .B (out[15]), .S (en), .Y (n_28));
  MUX2X1 g71(.A (n_87), .B (out[16]), .S (en), .Y (n_27));
  MUX2X1 g72(.A (n_86), .B (out[17]), .S (en), .Y (n_26));
  MUX2X1 g73(.A (n_85), .B (out[18]), .S (en), .Y (n_25));
  MUX2X1 g74(.A (n_84), .B (out[19]), .S (en), .Y (n_24));
  MUX2X1 g75(.A (n_102), .B (out[1]), .S (en), .Y (n_23));
  MUX2X1 g76(.A (n_101), .B (out[2]), .S (en), .Y (n_22));
  MUX2X1 g77(.A (n_100), .B (out[3]), .S (en), .Y (n_21));
  MUX2X1 g78(.A (n_99), .B (out[4]), .S (en), .Y (n_20));
  INVX1 g79(.A (n_10), .Y (n_19));
  INVX1 g80(.A (n_9), .Y (n_18));
  INVX1 g81(.A (n_8), .Y (n_17));
  INVX1 g82(.A (n_7), .Y (n_16));
  INVX1 g83(.A (n_6), .Y (n_15));
  INVX1 g84(.A (n_5), .Y (n_14));
  INVX1 g85(.A (n_4), .Y (n_13));
  INVX1 g86(.A (n_3), .Y (n_12));
  INVX1 g87(.A (n_2), .Y (n_11));
  MUX2X1 g88(.A (n_93), .B (out[10]), .S (en), .Y (n_10));
  MUX2X1 g89(.A (n_98), .B (out[5]), .S (en), .Y (n_9));
  MUX2X1 g90(.A (n_97), .B (out[6]), .S (en), .Y (n_8));
  MUX2X1 g91(.A (n_92), .B (out[11]), .S (en), .Y (n_7));
  MUX2X1 g92(.A (n_91), .B (out[12]), .S (en), .Y (n_6));
  MUX2X1 g93(.A (n_96), .B (out[7]), .S (en), .Y (n_5));
  MUX2X1 g94(.A (n_95), .B (out[8]), .S (en), .Y (n_4));
  MUX2X1 g95(.A (n_94), .B (out[9]), .S (en), .Y (n_3));
  MUX2X1 g96(.A (n_90), .B (out[13]), .S (en), .Y (n_2));
  BUFX2 drc_bufs179(.A (n_59), .Y (out[19]));
  BUFX2 drc_bufs180(.A (n_40), .Y (out[0]));
  BUFX2 drc_bufs181(.A (n_41), .Y (out[1]));
  BUFX2 drc_bufs182(.A (n_42), .Y (out[2]));
  BUFX2 drc_bufs183(.A (n_43), .Y (out[3]));
  BUFX2 drc_bufs184(.A (n_44), .Y (out[4]));
  BUFX2 drc_bufs185(.A (n_45), .Y (out[5]));
  BUFX2 drc_bufs186(.A (n_46), .Y (out[6]));
  BUFX2 drc_bufs187(.A (n_47), .Y (out[7]));
  BUFX2 drc_bufs188(.A (n_48), .Y (out[8]));
  BUFX2 drc_bufs189(.A (n_49), .Y (out[9]));
  BUFX2 drc_bufs190(.A (n_50), .Y (out[10]));
  BUFX2 drc_bufs191(.A (n_51), .Y (out[11]));
  BUFX2 drc_bufs192(.A (n_52), .Y (out[12]));
  BUFX2 drc_bufs193(.A (n_53), .Y (out[13]));
  BUFX2 drc_bufs194(.A (n_54), .Y (out[14]));
  BUFX2 drc_bufs195(.A (n_55), .Y (out[15]));
  BUFX2 drc_bufs196(.A (n_56), .Y (out[16]));
  BUFX2 drc_bufs197(.A (n_57), .Y (out[17]));
  BUFX2 drc_bufs198(.A (n_58), .Y (out[18]));
  XOR2X1 g2(.A (en), .B (out[0]), .Y (n_0));
endmodule

module dsc_mul(a, b, z, clk, rst, en, ov);
  input [9:0] a, b;
  input clk, rst, en;
  output [19:0] z;
  output ov;
  wire [9:0] a, b;
  wire clk, rst, en;
  wire [19:0] z;
  wire ov;
  wire ctr_ov_a, dummy_ov, sn_out_a, sn_out_b, sn_out_mul;
  det_stoch_mul mul(.a (sn_out_a), .b (sn_out_b), .y (sn_out_mul));
  prg_10b prg_a(.clk (clk), .rst (rst), .en (en), .bin_in (a), .sn_out
       (sn_out_a), .ctr_overflow (ctr_ov_a));
  prg_10b_1 prg_b(.clk (ctr_ov_a), .rst (rst), .en (en), .bin_in (b),
       .sn_out (sn_out_b), .ctr_overflow (ov));
  counter_WIDTH20 stoch2bin_out(.out (z), .clk (clk), .en (sn_out_mul),
       .rst (rst), .overflow (dummy_ov));
endmodule

