NAME_TOP := MY_NAME_TOP
USERNAME := $(shell whoami)

synth:
	rc -file rc.tcl



#----- Cleanup
# Delete temporary files
clean:
	@rm -rf *.rpt*
	@rm -rf fv
	@rm -rf *.log*
	@rm -rf libscore_work
	@rm -rf *.cmd*
	@rm -rf $(NAME_TOP)_netlist.v





