
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mul_es_naive 

module prg_4b_1(clk, rst, en, bin_in, sn_out, ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in;
  wire sn_out, ctr_overflow;
  wire [3:0] ctr4_out;
  wire n_0, n_1, n_3, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_46, n_47;
  OAI21X1 g223(.A (ctr4_out[3]), .B (n_35), .C (n_36), .Y (sn_out));
  OAI21X1 g224(.A (n_30), .B (n_34), .C (bin_in[3]), .Y (n_36));
  NOR3X1 g225(.A (bin_in[3]), .B (n_30), .C (n_34), .Y (n_35));
  AND2X1 g226(.A (n_23), .B (n_33), .Y (n_34));
  OAI21X1 g227(.A (n_25), .B (ctr4_out[0]), .C (ctr4_out[1]), .Y
       (n_33));
  AOI21X1 g228(.A (n_27), .B (ctr4_out[2]), .C (n_24), .Y (n_32));
  AOI21X1 g229(.A (bin_in[0]), .B (n_26), .C (bin_in[1]), .Y (n_31));
  AND2X1 g230(.A (n_28), .B (bin_in[2]), .Y (n_30));
  NAND2X1 g231(.A (bin_in[1]), .B (bin_in[0]), .Y (n_29));
  INVX1 g232(.A (ctr4_out[2]), .Y (n_28));
  INVX1 g233(.A (bin_in[2]), .Y (n_27));
  INVX1 g234(.A (ctr4_out[0]), .Y (n_26));
  BUFX2 drc_bufs(.A (n_29), .Y (n_25));
  BUFX2 drc_bufs235(.A (n_31), .Y (n_24));
  BUFX2 drc_bufs236(.A (n_32), .Y (n_23));
  DFFSR \ctr4_out_reg[3] (.R (n_5), .S (1'b1), .CLK (clk), .D (n_47),
       .Q (n_18));
  DFFSR \ctr4_out_reg[2] (.R (n_5), .S (1'b1), .CLK (clk), .D (n_16),
       .Q (n_19));
  INVX1 g116(.A (n_15), .Y (n_16));
  MUX2X1 g117(.A (n_12), .B (ctr4_out[2]), .S (en), .Y (n_15));
  DFFSR ctr4_overflow_reg(.R (n_5), .S (1'b1), .CLK (clk), .D (n_13),
       .Q (n_22));
  DFFSR \ctr4_out_reg[1] (.R (n_5), .S (1'b1), .CLK (clk), .D (n_10),
       .Q (n_20));
  MUX2X1 g121(.A (n_1), .B (n_3), .S (en), .Y (n_13));
  HAX1 g122(.A (ctr4_out[2]), .B (n_7), .YC (n_11), .YS (n_12));
  INVX1 g123(.A (n_9), .Y (n_10));
  MUX2X1 g124(.A (n_6), .B (ctr4_out[1]), .S (en), .Y (n_9));
  NAND3X1 g125(.A (ctr4_out[2]), .B (ctr4_out[3]), .C (n_7), .Y (n_8));
  DFFSR \ctr4_out_reg[0] (.R (n_5), .S (1'b1), .CLK (clk), .D (n_0), .Q
       (n_21));
  HAX1 g127(.A (ctr4_out[1]), .B (ctr4_out[0]), .YC (n_7), .YS (n_6));
  INVX1 g142(.A (rst), .Y (n_5));
  INVX1 drc_bufs157(.A (ctr_overflow), .Y (n_3));
  BUFX2 drc_bufs163(.A (n_8), .Y (n_1));
  BUFX2 drc_bufs164(.A (n_22), .Y (ctr_overflow));
  BUFX2 drc_bufs165(.A (n_21), .Y (ctr4_out[0]));
  BUFX2 drc_bufs166(.A (n_18), .Y (ctr4_out[3]));
  BUFX2 drc_bufs167(.A (n_19), .Y (ctr4_out[2]));
  BUFX2 drc_bufs168(.A (n_20), .Y (ctr4_out[1]));
  XOR2X1 g2(.A (en), .B (ctr4_out[0]), .Y (n_0));
  XOR2X1 g240(.A (n_46), .B (ctr4_out[3]), .Y (n_47));
  AND2X1 g3(.A (n_11), .B (en), .Y (n_46));
endmodule

module dsc_mul_es_naive(a, b, z, clk, rst, en, ov);
  input [3:0] a, b;
  input clk, rst, en;
  output [7:0] z;
  output ov;
  wire [3:0] a, b;
  wire clk, rst, en;
  wire [7:0] z;
  wire ov;
  wire [3:0] prg_a_ctr4_out;
  wire ctr_ov_a, ctr_ov_b, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, sn_out_b;
  prg_4b_1 prg_b(.clk (ctr_ov_a), .rst (rst), .en (en), .bin_in (b),
       .sn_out (sn_out_b), .ctr_overflow (ctr_ov_b));
  OR2X1 g53(.A (n_16), .B (ctr_ov_b), .Y (ov));
  INVX1 g54(.A (sn_out_b), .Y (n_16));
  DFFSR \stoch2bin_out_out_reg[7] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_64), .Q (n_73));
  OAI21X1 g512(.A (n_33), .B (n_61), .C (n_2), .Y (n_64));
  DFFSR \stoch2bin_out_out_reg[6] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_63), .Q (n_72));
  INVX1 g514(.A (n_62), .Y (n_63));
  MUX2X1 g515(.A (z[6]), .B (n_60), .S (n_33), .Y (n_62));
  XNOR2X1 g516(.A (n_59), .B (z[7]), .Y (n_61));
  DFFSR \stoch2bin_out_out_reg[5] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_58), .Q (n_71));
  HAX1 g518(.A (z[6]), .B (n_55), .YC (n_59), .YS (n_60));
  INVX1 g519(.A (n_57), .Y (n_58));
  MUX2X1 g520(.A (z[5]), .B (n_56), .S (n_33), .Y (n_57));
  DFFSR \stoch2bin_out_out_reg[4] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_54), .Q (n_70));
  HAX1 g522(.A (z[5]), .B (n_51), .YC (n_55), .YS (n_56));
  INVX1 g523(.A (n_53), .Y (n_54));
  MUX2X1 g524(.A (z[4]), .B (n_52), .S (n_33), .Y (n_53));
  DFFSR \stoch2bin_out_out_reg[3] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_50), .Q (n_69));
  DFFSR \prg_a_ctr4_out_reg[3] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_48), .Q (prg_a_ctr4_out[3]));
  DFFSR prg_a_ctr4_overflow_reg(.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_46), .Q (ctr_ov_a));
  HAX1 g528(.A (z[4]), .B (n_43), .YC (n_51), .YS (n_52));
  INVX1 g529(.A (n_49), .Y (n_50));
  MUX2X1 g530(.A (z[3]), .B (n_44), .S (n_33), .Y (n_49));
  INVX1 g531(.A (n_47), .Y (n_48));
  MUX2X1 g532(.A (n_42), .B (n_9), .S (en), .Y (n_47));
  INVX1 g533(.A (n_45), .Y (n_46));
  MUX2X1 g534(.A (n_41), .B (ctr_ov_a), .S (en), .Y (n_45));
  DFFSR \stoch2bin_out_out_reg[1] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_40), .Q (n_67));
  DFFSR \stoch2bin_out_out_reg[2] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_38), .Q (n_68));
  DFFSR \stoch2bin_out_out_reg[0] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_1), .Q (n_66));
  HAX1 g538(.A (z[3]), .B (n_30), .YC (n_43), .YS (n_44));
  HAX1 g539(.A (n_9), .B (n_28), .YC (n_41), .YS (n_42));
  DFFSR \prg_a_ctr4_out_reg[2] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_35), .Q (prg_a_ctr4_out[2]));
  INVX1 g541(.A (n_39), .Y (n_40));
  MUX2X1 g542(.A (z[1]), .B (n_24), .S (n_33), .Y (n_39));
  INVX1 g543(.A (n_37), .Y (n_38));
  MUX2X1 g544(.A (z[2]), .B (n_31), .S (n_33), .Y (n_37));
  NAND2X1 g546(.A (z[7]), .B (n_33), .Y (n_36));
  INVX1 g547(.A (n_34), .Y (n_35));
  MUX2X1 g548(.A (n_29), .B (n_8), .S (en), .Y (n_34));
  OR2X1 g550(.A (n_16), .B (n_4), .Y (n_33));
  DFFSR \prg_a_ctr4_out_reg[1] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_27), .Q (prg_a_ctr4_out[1]));
  AOI22X1 g552(.A (n_25), .B (n_5), .C (a[3]), .D (n_10), .Y (n_32));
  HAX1 g553(.A (z[2]), .B (n_23), .YC (n_30), .YS (n_31));
  HAX1 g554(.A (n_8), .B (n_21), .YC (n_28), .YS (n_29));
  INVX1 g555(.A (n_26), .Y (n_27));
  MUX2X1 g556(.A (n_22), .B (n_6), .S (en), .Y (n_26));
  OAI21X1 g557(.A (n_7), .B (n_20), .C (n_3), .Y (n_25));
  DFFSR \prg_a_ctr4_out_reg[0] (.R (n_15), .S (1'b1), .CLK (clk), .D
       (n_0), .Q (prg_a_ctr4_out[0]));
  HAX1 g559(.A (z[1]), .B (z[0]), .YC (n_23), .YS (n_24));
  HAX1 g560(.A (n_6), .B (n_7), .YC (n_21), .YS (n_22));
  OAI21X1 g561(.A (a[1]), .B (n_11), .C (a[0]), .Y (n_20));
  AOI22X1 g562(.A (n_12), .B (a[2]), .C (a[1]), .D (n_11), .Y (n_19));
  AOI22X1 g563(.A (n_8), .B (n_17), .C (n_14), .D (n_9), .Y (n_18));
  INVX1 g585(.A (a[2]), .Y (n_17));
  INVX1 g587(.A (rst), .Y (n_15));
  INVX1 g588(.A (a[3]), .Y (n_14));
  INVX1 drc_bufs623(.A (n_9), .Y (n_10));
  INVX1 drc_bufs627(.A (n_8), .Y (n_12));
  INVX1 drc_bufs635(.A (n_6), .Y (n_11));
  BUFX2 drc_bufs641(.A (n_18), .Y (n_5));
  BUFX2 drc_bufs642(.A (n_32), .Y (n_4));
  BUFX2 drc_bufs643(.A (n_19), .Y (n_3));
  BUFX2 drc_bufs644(.A (n_36), .Y (n_2));
  BUFX2 drc_bufs645(.A (n_73), .Y (z[7]));
  BUFX2 drc_bufs646(.A (n_72), .Y (z[6]));
  BUFX2 drc_bufs647(.A (n_70), .Y (z[4]));
  BUFX2 drc_bufs648(.A (n_66), .Y (z[0]));
  BUFX2 drc_bufs650(.A (prg_a_ctr4_out[3]), .Y (n_9));
  BUFX2 drc_bufs651(.A (prg_a_ctr4_out[2]), .Y (n_8));
  BUFX2 drc_bufs652(.A (prg_a_ctr4_out[1]), .Y (n_6));
  BUFX2 drc_bufs653(.A (n_69), .Y (z[3]));
  BUFX2 drc_bufs654(.A (prg_a_ctr4_out[0]), .Y (n_7));
  BUFX2 drc_bufs655(.A (n_71), .Y (z[5]));
  BUFX2 drc_bufs656(.A (n_67), .Y (z[1]));
  BUFX2 drc_bufs657(.A (n_68), .Y (z[2]));
  XNOR2X1 g2(.A (n_33), .B (z[0]), .Y (n_1));
  XOR2X1 g675(.A (en), .B (n_7), .Y (n_0));
endmodule

