
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/array_mul 

module FA_6(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (cin), .B (a), .C (b), .YC (cout), .YS (s));
endmodule

module FA_7(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (a), .B (b), .C (cin), .YC (cout), .YS (s));
endmodule

module FA(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (cin), .B (b), .C (a), .YC (cout), .YS (s));
endmodule

module FA_1(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (cin), .B (b), .C (a), .YC (cout), .YS (s));
endmodule

module FA_2(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (cin), .B (a), .C (b), .YC (cout), .YS (s));
endmodule

module FA_3(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (cin), .B (b), .C (a), .YC (cout), .YS (s));
endmodule

module FA_4(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (cin), .B (a), .C (b), .YC (cout), .YS (s));
endmodule

module FA_5(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  FAX1 g2(.A (cin), .B (a), .C (b), .YC (cout), .YS (s));
endmodule

module HA(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  HAX1 g17(.A (b), .B (a), .YC (cout), .YS (s));
endmodule

module HA_1(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  HAX1 g17(.A (b), .B (a), .YC (cout), .YS (s));
endmodule

module HA_2(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  HAX1 g17(.A (b), .B (a), .YC (cout), .YS (s));
endmodule

module HA_3(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  HAX1 g17(.A (b), .B (a), .YC (cout), .YS (s));
endmodule

module array_mul(a, b, z);
  input [3:0] a, b;
  output [7:0] z;
  wire [3:0] a, b;
  wire [7:0] z;
  wire [11:0] s;
  wire [11:0] c;
  wire \c[0]_1 , pp01, pp02, pp03, pp10, pp11, pp12, pp13;
  wire pp20, pp22, pp23, pp30, pp31, pp32, pp33;
  FA_6 fa10(.a (s[8]), .b (c[7]), .cin (c[9]), .s (z[5]), .cout
       (c[10]));
  FA_7 fa11(.a (pp33), .b (c[8]), .cin (c[10]), .s (z[6]), .cout
       (z[7]));
  FA fa3(.a (s[1]), .b (\c[0]_1 ), .cin (pp02), .s (z[2]), .cout
       (c[3]));
  FA_1 fa4(.a (s[2]), .b (c[1]), .cin (pp12), .s (s[4]), .cout (c[4]));
  FA_2 fa5(.a (pp31), .b (c[2]), .cin (pp22), .s (s[5]), .cout (c[5]));
  FA_3 fa6(.a (s[4]), .b (c[3]), .cin (pp03), .s (z[3]), .cout (c[6]));
  FA_4 fa7(.a (s[5]), .b (c[4]), .cin (pp13), .s (s[7]), .cout (c[7]));
  FA_5 fa8(.a (pp32), .b (c[5]), .cin (pp23), .s (s[8]), .cout (c[8]));
  HA ha0(.a (pp10), .b (pp01), .s (z[1]), .cout (\c[0]_1 ));
  HA_1 ha1(.a (pp20), .b (pp11), .s (s[1]), .cout (c[1]));
  HA_2 ha2(.a (pp30), .b (pp31), .s (s[2]), .cout (c[2]));
  HA_3 ha9(.a (s[7]), .b (c[6]), .s (z[4]), .cout (c[9]));
  AND2X1 g106(.A (a[0]), .B (b[0]), .Y (z[0]));
  AND2X1 g107(.A (a[2]), .B (b[2]), .Y (pp22));
  AND2X1 g108(.A (a[2]), .B (b[0]), .Y (pp20));
  AND2X1 g109(.A (a[3]), .B (b[0]), .Y (pp30));
  AND2X1 g110(.A (a[1]), .B (b[2]), .Y (pp12));
  AND2X1 g111(.A (a[0]), .B (b[2]), .Y (pp02));
  AND2X1 g112(.A (a[0]), .B (b[3]), .Y (pp03));
  AND2X1 g113(.A (a[1]), .B (b[0]), .Y (pp10));
  AND2X1 g114(.A (a[3]), .B (b[1]), .Y (pp31));
  AND2X1 g115(.A (a[1]), .B (b[1]), .Y (pp11));
  AND2X1 g116(.A (a[0]), .B (b[1]), .Y (pp01));
  AND2X1 g117(.A (a[1]), .B (b[3]), .Y (pp13));
  AND2X1 g118(.A (a[2]), .B (b[3]), .Y (pp23));
  AND2X1 g119(.A (a[3]), .B (b[2]), .Y (pp32));
  AND2X1 g120(.A (a[3]), .B (b[3]), .Y (pp33));
endmodule

