
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dsc_mul_es_imp 

module prg_4b_min(clk, rst, en, bin_in_a, bin_in_b, sn_out,
     ctr_overflow);
  input clk, rst, en;
  input [3:0] bin_in_a, bin_in_b;
  output sn_out, ctr_overflow;
  wire clk, rst, en;
  wire [3:0] bin_in_a, bin_in_b;
  wire sn_out, ctr_overflow;
  wire [3:0] prg_ab_ctr4_out;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60;
  OR2X1 g378(.A (n_25), .B (n_59), .Y (sn_out));
  AOI22X1 g379(.A (n_28), .B (n_53), .C (n_52), .D (n_29), .Y (n_60));
  NOR3X1 g380(.A (n_32), .B (prg_ab_ctr4_out[3]), .C (n_58), .Y (n_59));
  NOR3X1 g381(.A (bin_in_a[3]), .B (n_54), .C (n_55), .Y (n_58));
  AOI21X1 g382(.A (bin_in_a[3]), .B (n_35), .C (n_55), .Y (n_57));
  NAND3X1 g383(.A (n_37), .B (n_51), .C (n_49), .Y (n_56));
  NOR3X1 g384(.A (n_41), .B (n_50), .C (n_30), .Y (n_55));
  INVX1 g385(.A (n_53), .Y (n_54));
  OR2X1 g386(.A (n_24), .B (n_42), .Y (n_53));
  OR2X1 g387(.A (n_26), .B (n_43), .Y (n_52));
  OAI21X1 g388(.A (n_27), .B (prg_ab_ctr4_out[1]), .C
       (prg_ab_ctr4_out[2]), .Y (n_51));
  AND2X1 g389(.A (n_23), .B (prg_ab_ctr4_out[2]), .Y (n_50));
  INVX1 g390(.A (n_22), .Y (n_49));
  AOI21X1 g391(.A (bin_in_b[1]), .B (n_34), .C (bin_in_b[2]), .Y
       (n_48));
  NAND3X1 g392(.A (bin_in_a[1]), .B (bin_in_a[2]), .C (n_34), .Y
       (n_47));
  AOI21X1 g393(.A (bin_in_a[1]), .B (n_34), .C (bin_in_a[2]), .Y
       (n_46));
  NAND3X1 g394(.A (bin_in_b[0]), .B (n_33), .C (n_37), .Y (n_45));
  NAND3X1 g395(.A (bin_in_a[0]), .B (n_33), .C (n_40), .Y (n_44));
  OAI21X1 g396(.A (bin_in_b[1]), .B (n_34), .C (n_39), .Y (n_43));
  OAI21X1 g397(.A (bin_in_a[1]), .B (n_34), .C (n_38), .Y (n_42));
  INVX1 g398(.A (n_40), .Y (n_41));
  OR2X1 g399(.A (n_35), .B (bin_in_a[3]), .Y (n_40));
  OR2X1 g400(.A (n_31), .B (bin_in_b[2]), .Y (n_39));
  OR2X1 g401(.A (n_31), .B (bin_in_a[2]), .Y (n_38));
  OR2X1 g402(.A (n_35), .B (bin_in_b[3]), .Y (n_37));
  NAND2X1 g403(.A (bin_in_b[2]), .B (bin_in_b[1]), .Y (n_36));
  INVX1 g404(.A (prg_ab_ctr4_out[3]), .Y (n_35));
  INVX1 g405(.A (prg_ab_ctr4_out[1]), .Y (n_34));
  INVX1 g406(.A (prg_ab_ctr4_out[0]), .Y (n_33));
  INVX1 g407(.A (bin_in_b[3]), .Y (n_32));
  INVX1 g408(.A (prg_ab_ctr4_out[2]), .Y (n_31));
  BUFX2 drc_bufs(.A (n_46), .Y (n_30));
  BUFX2 drc_bufs409(.A (n_56), .Y (n_29));
  BUFX2 drc_bufs410(.A (n_57), .Y (n_28));
  BUFX2 drc_bufs411(.A (n_36), .Y (n_27));
  BUFX2 drc_bufs412(.A (n_45), .Y (n_26));
  BUFX2 drc_bufs413(.A (n_60), .Y (n_25));
  BUFX2 drc_bufs414(.A (n_44), .Y (n_24));
  BUFX2 drc_bufs415(.A (n_47), .Y (n_23));
  BUFX2 drc_bufs416(.A (n_48), .Y (n_22));
  DFFSR \prg_ab_ctr4_out_reg[3] (.R (n_2), .S (1'b1), .CLK (clk), .D
       (n_14), .Q (n_17));
  DFFSR prg_ab_ctr4_overflow_reg(.R (n_2), .S (1'b1), .CLK (clk), .D
       (n_16), .Q (n_21));
  INVX1 g117(.A (n_15), .Y (n_16));
  MUX2X1 g118(.A (n_11), .B (ctr_overflow), .S (en), .Y (n_15));
  INVX1 g119(.A (n_13), .Y (n_14));
  MUX2X1 g120(.A (n_12), .B (prg_ab_ctr4_out[3]), .S (en), .Y (n_13));
  DFFSR \prg_ab_ctr4_out_reg[2] (.R (n_2), .S (1'b1), .CLK (clk), .D
       (n_10), .Q (n_18));
  HAX1 g122(.A (prg_ab_ctr4_out[3]), .B (n_7), .YC (n_11), .YS (n_12));
  INVX1 g123(.A (n_9), .Y (n_10));
  MUX2X1 g124(.A (n_8), .B (prg_ab_ctr4_out[2]), .S (en), .Y (n_9));
  DFFSR \prg_ab_ctr4_out_reg[1] (.R (n_2), .S (1'b1), .CLK (clk), .D
       (n_6), .Q (n_19));
  HAX1 g126(.A (prg_ab_ctr4_out[2]), .B (n_3), .YC (n_7), .YS (n_8));
  INVX1 g127(.A (n_5), .Y (n_6));
  MUX2X1 g128(.A (n_4), .B (prg_ab_ctr4_out[1]), .S (en), .Y (n_5));
  DFFSR \prg_ab_ctr4_out_reg[0] (.R (n_2), .S (1'b1), .CLK (clk), .D
       (n_0), .Q (n_20));
  HAX1 g130(.A (prg_ab_ctr4_out[1]), .B (prg_ab_ctr4_out[0]), .YC
       (n_3), .YS (n_4));
  INVX1 g140(.A (rst), .Y (n_2));
  BUFX2 drc_bufs161(.A (n_21), .Y (ctr_overflow));
  BUFX2 drc_bufs162(.A (n_17), .Y (prg_ab_ctr4_out[3]));
  BUFX2 drc_bufs163(.A (n_18), .Y (prg_ab_ctr4_out[2]));
  BUFX2 drc_bufs164(.A (n_19), .Y (prg_ab_ctr4_out[1]));
  BUFX2 drc_bufs165(.A (n_20), .Y (prg_ab_ctr4_out[0]));
  XOR2X1 g2(.A (en), .B (prg_ab_ctr4_out[0]), .Y (n_0));
endmodule

module dsc_mul_es_imp(a, b, z, clk, rst, en, ov);
  input [3:0] a, b;
  input clk, rst, en;
  output [7:0] z;
  output ov;
  wire [3:0] a, b;
  wire clk, rst, en;
  wire [7:0] z;
  wire ov;
  wire [3:0] prg_a_prg_ab_ctr4_out;
  wire ctr_ov_a, ctr_ov_b, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, sn_out_b;
  prg_4b_min prg_b(.clk (ctr_ov_a), .rst (rst), .en (en), .bin_in_a
       (a), .bin_in_b (b), .sn_out (sn_out_b), .ctr_overflow
       (ctr_ov_b));
  OR2X1 g61(.A (n_92), .B (ctr_ov_b), .Y (ov));
  INVX1 g62(.A (sn_out_b), .Y (n_92));
  DFFSR \stoch2bin_out_out_reg[7] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_82), .Q (n_91));
  OAI21X1 g491(.A (n_57), .B (n_79), .C (n_4), .Y (n_82));
  DFFSR \stoch2bin_out_out_reg[6] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_81), .Q (n_90));
  INVX1 g493(.A (n_80), .Y (n_81));
  MUX2X1 g494(.A (z[6]), .B (n_78), .S (n_57), .Y (n_80));
  XNOR2X1 g495(.A (n_77), .B (z[7]), .Y (n_79));
  DFFSR \stoch2bin_out_out_reg[5] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_76), .Q (n_89));
  HAX1 g497(.A (z[6]), .B (n_73), .YC (n_77), .YS (n_78));
  INVX1 g498(.A (n_75), .Y (n_76));
  MUX2X1 g499(.A (z[5]), .B (n_74), .S (n_57), .Y (n_75));
  DFFSR \stoch2bin_out_out_reg[4] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_72), .Q (n_88));
  HAX1 g501(.A (z[5]), .B (n_69), .YC (n_73), .YS (n_74));
  INVX1 g502(.A (n_71), .Y (n_72));
  MUX2X1 g503(.A (z[4]), .B (n_70), .S (n_57), .Y (n_71));
  DFFSR \stoch2bin_out_out_reg[1] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_64), .Q (n_85));
  DFFSR \stoch2bin_out_out_reg[2] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_62), .Q (n_86));
  DFFSR \stoch2bin_out_out_reg[3] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_60), .Q (n_87));
  DFFSR \prg_a_prg_ab_ctr4_out_reg[3] (.R (n_19), .S (1'b1), .CLK
       (clk), .D (n_66), .Q (prg_a_prg_ab_ctr4_out[3]));
  DFFSR prg_a_prg_ab_ctr4_overflow_reg(.R (n_19), .S (1'b1), .CLK
       (clk), .D (n_68), .Q (ctr_ov_a));
  DFFSR \stoch2bin_out_out_reg[0] (.R (n_19), .S (1'b1), .CLK (clk), .D
       (n_1), .Q (n_84));
  HAX1 g510(.A (z[4]), .B (n_55), .YC (n_69), .YS (n_70));
  INVX1 g511(.A (n_67), .Y (n_68));
  MUX2X1 g512(.A (n_53), .B (ctr_ov_a), .S (en), .Y (n_67));
  INVX1 g513(.A (n_65), .Y (n_66));
  MUX2X1 g514(.A (n_54), .B (n_13), .S (en), .Y (n_65));
  INVX1 g515(.A (n_63), .Y (n_64));
  MUX2X1 g516(.A (z[1]), .B (n_28), .S (n_57), .Y (n_63));
  INVX1 g517(.A (n_61), .Y (n_62));
  MUX2X1 g518(.A (z[2]), .B (n_46), .S (n_57), .Y (n_61));
  INVX1 g519(.A (n_59), .Y (n_60));
  MUX2X1 g520(.A (z[3]), .B (n_56), .S (n_57), .Y (n_59));
  NAND2X1 g522(.A (z[7]), .B (n_57), .Y (n_58));
  DFFSR \prg_a_prg_ab_ctr4_out_reg[2] (.R (n_19), .S (1'b1), .CLK
       (clk), .D (n_52), .Q (prg_a_prg_ab_ctr4_out[2]));
  OAI21X1 g525(.A (n_7), .B (n_10), .C (sn_out_b), .Y (n_57));
  HAX1 g526(.A (z[3]), .B (n_45), .YC (n_55), .YS (n_56));
  HAX1 g527(.A (n_13), .B (n_43), .YC (n_53), .YS (n_54));
  INVX1 g528(.A (n_51), .Y (n_52));
  MUX2X1 g529(.A (n_44), .B (n_14), .S (en), .Y (n_51));
  NAND3X1 g530(.A (n_6), .B (n_9), .C (n_47), .Y (n_50));
  NAND3X1 g531(.A (n_5), .B (n_8), .C (n_48), .Y (n_49));
  DFFSR \prg_a_prg_ab_ctr4_out_reg[1] (.R (n_19), .S (1'b1), .CLK
       (clk), .D (n_40), .Q (prg_a_prg_ab_ctr4_out[1]));
  OR2X1 g533(.A (n_41), .B (n_12), .Y (n_48));
  OR2X1 g534(.A (n_42), .B (n_12), .Y (n_47));
  HAX1 g535(.A (z[2]), .B (n_27), .YC (n_45), .YS (n_46));
  HAX1 g536(.A (n_14), .B (n_25), .YC (n_43), .YS (n_44));
  OAI21X1 g537(.A (n_36), .B (n_35), .C (b[0]), .Y (n_42));
  OAI21X1 g538(.A (n_32), .B (n_30), .C (a[0]), .Y (n_41));
  INVX1 g539(.A (n_39), .Y (n_40));
  MUX2X1 g540(.A (n_26), .B (n_11), .S (en), .Y (n_39));
  AOI22X1 g541(.A (n_30), .B (a[1]), .C (a[3]), .D (n_16), .Y (n_38));
  AOI22X1 g542(.A (n_35), .B (b[1]), .C (b[3]), .D (n_16), .Y (n_37));
  DFFSR \prg_a_prg_ab_ctr4_out_reg[0] (.R (n_19), .S (1'b1), .CLK
       (clk), .D (n_0), .Q (prg_a_prg_ab_ctr4_out[0]));
  AND2X1 g544(.A (n_24), .B (b[1]), .Y (n_36));
  AND2X1 g545(.A (n_24), .B (n_17), .Y (n_35));
  NAND3X1 g546(.A (a[2]), .B (n_15), .C (n_22), .Y (n_34));
  NAND3X1 g547(.A (b[2]), .B (n_15), .C (n_20), .Y (n_33));
  INVX1 g548(.A (n_3), .Y (n_32));
  NAND3X1 g549(.A (a[1]), .B (n_22), .C (n_21), .Y (n_31));
  INVX1 g550(.A (n_2), .Y (n_30));
  NAND3X1 g551(.A (n_17), .B (n_22), .C (n_21), .Y (n_29));
  HAX1 g552(.A (z[1]), .B (z[0]), .YC (n_27), .YS (n_28));
  HAX1 g553(.A (n_11), .B (n_12), .YC (n_25), .YS (n_26));
  INVX1 g554(.A (n_23), .Y (n_24));
  OAI21X1 g555(.A (b[2]), .B (n_15), .C (n_20), .Y (n_23));
  OR2X1 g557(.A (n_16), .B (a[3]), .Y (n_22));
  OR2X1 g558(.A (n_15), .B (a[2]), .Y (n_21));
  OR2X1 g559(.A (n_16), .B (b[3]), .Y (n_20));
  INVX1 g587(.A (rst), .Y (n_19));
  INVX1 drc_bufs589(.A (n_14), .Y (n_15));
  INVX1 drc_bufs593(.A (n_13), .Y (n_16));
  INVX1 drc_bufs633(.A (n_11), .Y (n_17));
  BUFX2 drc_bufs639(.A (n_49), .Y (n_10));
  BUFX2 drc_bufs640(.A (n_37), .Y (n_9));
  BUFX2 drc_bufs641(.A (n_38), .Y (n_8));
  BUFX2 drc_bufs642(.A (n_50), .Y (n_7));
  BUFX2 drc_bufs643(.A (n_33), .Y (n_6));
  BUFX2 drc_bufs644(.A (n_34), .Y (n_5));
  BUFX2 drc_bufs645(.A (n_58), .Y (n_4));
  BUFX2 drc_bufs646(.A (n_31), .Y (n_3));
  BUFX2 drc_bufs647(.A (n_29), .Y (n_2));
  BUFX2 drc_bufs648(.A (n_91), .Y (z[7]));
  BUFX2 drc_bufs649(.A (n_90), .Y (z[6]));
  BUFX2 drc_bufs650(.A (n_88), .Y (z[4]));
  BUFX2 drc_bufs651(.A (n_84), .Y (z[0]));
  BUFX2 drc_bufs653(.A (n_87), .Y (z[3]));
  BUFX2 drc_bufs654(.A (prg_a_prg_ab_ctr4_out[0]), .Y (n_12));
  BUFX2 drc_bufs655(.A (prg_a_prg_ab_ctr4_out[1]), .Y (n_11));
  BUFX2 drc_bufs656(.A (n_89), .Y (z[5]));
  BUFX2 drc_bufs657(.A (n_86), .Y (z[2]));
  BUFX2 drc_bufs658(.A (prg_a_prg_ab_ctr4_out[2]), .Y (n_14));
  BUFX2 drc_bufs659(.A (prg_a_prg_ab_ctr4_out[3]), .Y (n_13));
  BUFX2 drc_bufs660(.A (n_85), .Y (z[1]));
  XNOR2X1 g2(.A (n_57), .B (z[0]), .Y (n_1));
  XOR2X1 g683(.A (en), .B (n_12), .Y (n_0));
endmodule

